### PR TITLE
docs: fix command error.

### PR DESCRIPTION
**Pull request by laingke**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Please update this section with detailed description.

**Related issues**

fix the command error

**Checklist:**

- [ ] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [x] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by zaunist** [comment]
Hi, @laingke `systemctl` is compatible with the `service` command, so `systemctl xxx start` can be executed, but I think `systemctl start xxx` maybe better.
How do you think ? @bzp2010

**Comment by laingke** [comment]
@zaunist refer to [Compatibility with SysV](https://www.freedesktop.org/wiki/Software/systemd/Incompatibilities/), I am worried about this compatibility. In fact, `systemctl xxx start` already unwork in CentOS 7/8, response with `Unknown operation 'xxx.service'`

**Review by zaunist — APPROVED** [review]

**Review by iamayushdas — APPROVED** [review]
LGTM

**Comment by zaunist** [comment]
cc @starsz @bzp2010 @nic-chen

**Review by nic-chen — APPROVED** [review]

**Review by bzp2010 — APPROVED** [review]

**Pull request merged**
