### PR TITLE
ci: remove push docker image to demo env

### PR DESCRIPTION
**Pull request by nic-chen**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

remove push docker image to demo env in Github Actions

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by juzhiyuan** [comment]
Hi, may I know visitors how to use the manager-api?

**Comment by zaunist** [comment]
If we delete the push step, the deploy-with-docker.yaml maybe delete together. Otherwise it doesn't make sense

**Comment by zaunist** [comment]
If we delete the push step, the deploy-with-docker.yaml maybe delete together. Otherwise it doesn't make sense

**Comment by nic-chen** [comment]
> Hi, may I know visitors how to use the manager-api?

They can still use the demo site, but we no longer push to deploy each commit, but use the release image on hub.docker to deploy.

**Comment by nic-chen** [comment]
> If we delete the push step, the deploy-with-docker.yaml maybe delete together. Otherwise it doesn't make sense

We still need to test Manager API under docker, especially whether there is a problem with the modification of the conf file

**Review by TakumiInui5432 — APPROVED** [review]

**Review by okaybase — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Comment by juzhiyuan** [comment]
ping @LiteSun

**Review by bzp2010 — APPROVED** [review]

**Pull request merged**
