### PR TITLE
chore: typo, `MangerApiExpect` should be `ManagerApiExpect`

### PR DESCRIPTION
**Pull request by nic-chen**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance

fix typo that `MangerApiExpect` should be `ManagerApiExpect`

### CODE REVIEW

**Review by membphis — APPROVED** [review]

**Review by membphis — CHANGES_REQUESTED** [review]
bad first commit log, please fix it first

image

**Comment by nic-chen** [comment]
> bad first commit log, please fix it first
> 
> image

fixed.

**Review by moonming — CHANGES_REQUESTED** [review]
please remove 666e8a203d8dcc968b526154a01f6eb40b077103

**Comment by nic-chen** [comment]
close, and will open a new pr

**Pull request closed without merging**
