### PR TITLE
feat: support regex_uri attribute in redirect plugin (#2434)

### LINKED ISSUE #2434: Feature request: support regex_uri attribute in redirect plugin
# Feature request

## Please describe your feature

image

APISIX already supports uri attribute in redirect plugin, which is under "custom" option in "Name And Description" section. But in some more complex situations, regex_uri would be a better way.

## Describe the solution you'd like

image

Add regex_uri support just like the proxy_rewrite plugin.

### PR DESCRIPTION
**Pull request by Sh1-5**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Support regex_uri attribute in redirect plugin.

**Related issues**

resolve #2434 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by guoqqqi** [comment]
Hi, @Sh1-5 Can you help to add the relevant E2E tests?

**Comment by Sh1-5** [comment]
> 你好，@Sh1-5您能帮忙添加相关的端到端测试吗？

ok, use cypress? I saw some of the original E2E tests failed

**Comment by guoqqqi** [comment]
Yes, because the PR has modified the UI of the redirect plugin, try modifying them and adding new test overlays.
If you encounter any problems, feel free to drop me a line～

**Comment by guoqqqi** [comment]
hello, @Sh1-5 Are you experiencing any difficulties, I see you have closed this PR

**Comment by guoqqqi** [comment]
Why did you submit a new PR? 😂
https://github.com/apache/apisix-dashboard/pull/2568

**Comment by Sh1-5** [comment]
> Why did you submit a new PR? 😂 #2568

I don't know if this project has a PR that can only contain one commit rule, so I submit a new PR that only contain one commit

**Comment by Sh1-5** [comment]
> > Why did you submit a new PR? 😂 #2568
> 
> I don't know if this project has a PR that can only contain one commit rule, so I submit a new PR that only contain one commit

All right, I forgot that git has a `rebase` command.....

**Comment by guoqqqi** [comment]
Don't worry, we don't have such a strange rule. We will help you review the content of the PR, so please continue to submit it later in the current PR.

**Comment by guoqqqi** [comment]
We will review your new PR. Let's continue to work in your new PR.

**Pull request closed without merging**
