### PR TITLE
feat: sync fields of `upstream` from APISIX

### PR DESCRIPTION
**Pull request by nic-chen**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

We has added two fields for `upstream` in APISIX. 

We only synchronized the schema in the previous version, and now we need to update the corresponding struct.

### CODE REVIEW

**Comment by starsz** [comment]
cc @juzhiyuan @LiteSun @liuxiran FE should know this.

**Comment by juzhiyuan** [comment]
No Backend coverage?

**Comment by nic-chen** [comment]
> No Backend coverage?

sometimes Codecov unstable.

**Comment by juzhiyuan** [comment]
Hi, please have a search at how many fields are mismatched between manager-api and admin-api, and sync them ASAP. This is needed to replace admin-api.

**Comment by juzhiyuan** [comment]
image

BTW, @LiteSun Please create an issue about why CodeCov misses some data occasionally.

**Comment by nic-chen** [comment]
> Hi, please have a search at how many fields are mismatched between manager-api and admin-api, and sync them ASAP. This is needed to replace admin-api.

This is all the fields that need to be synchronized for the resources that are already in use.

**Comment by nic-chen** [comment]
should add some more test cases for it, will update later.

**Comment by LiteSun** [comment]
> image
> 
> BTW, @LiteSun Please create an issue about why CodeCov misses some data occasionally.

Issue created.https://github.com/apache/apisix-dashboard/issues/1562

**Comment by nic-chen** [comment]
@starsz @tokers   please help review when you have time, thanks.

**Review by starsz — APPROVED** [review]

**Review by ShiningRush — APPROVED** [review]

**Pull request merged**
