### PR TITLE
docs: manager-api as os service

### LINKED ISSUE #842: feat: support run `manager api` as OS service
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [x] Feature or performance improvement
- [ ] Other

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

### PR DESCRIPTION
**Pull request by bisakhmondal**
**Why submit this pull request?**

- [x] docs

**What changes will this PR take into?**

Users guide.

**Related issues**
closes #842 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [x] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by juzhiyuan** [comment]
It seems that this PR gets pending due to CI issues...

**Review by iamayushdas — APPROVED** [review]
LGTM, Thank you

**Comment by juzhiyuan** [comment]
@bisakhmondal Hi, would you help to ask GitHub support for more information?

**Comment by bisakhmondal** [comment]
> @bisakhmondal Hi, would you help to ask GitHub support for more information?

Hi, I have opened a fresh ticket through GitHub support. I'll keep you posted about any new updates.
Thanks :)

**Review by nic-chen — APPROVED** [review]

**Review by starsz — APPROVED** [review]

**Comment by bisakhmondal** [comment]
Hi @juzhiyuan, got a reply from GitHub support.
image

Sounds good, isn't it. It seems we overthought, haha😄
Both of them has `path-ignore` set to `docs/**` :)

**Comment by imjoey** [comment]
@bisakhmondal @juzhiyuan The CI issue is due to set both `Frontend e2e test` and `run-test` as required checks. Apache Infra team has already fixed this, see https://issues.apache.org/jira/browse/INFRA-21906 for detail. We can merge this now.

**Review by imjoey — APPROVED** [review]
/lgtm
Thanks.

**Comment by bisakhmondal** [comment]
> @bisakhmondal @juzhiyuan The CI issue is due to set both `Frontend e2e test` and `run-test` as required checks. Apache Infra team has already fixed this, see https://issues.apache.org/jira/browse/INFRA-21906 for detail. We can merge this now.

Awesome @imjoey. Great work :) Thank you so much.

**Pull request merged**
