### PR TITLE
feat: searching upstream by users input while creating new routes

### LINKED ISSUE #1555: discuss: select upstream in the "Define API Backend Server" should provide a search function
# Feature request

## Please describe your feature

When selecting upstream in `Define API Backend Server` in `Create Route`, the function of searching upstream should be provided. Because the current selection of the upstream part is displayed through a list. When there are many upstreams, it is not easy for us to select the designated upstream. When choosing upstream, it would be better to provide a search upstream function.

截屏2021-03-04 下午5 18 27

## Describe the solution you'd like

When `Select Upstream`, the function of searching upstream should be added.

### PR DESCRIPTION
**Pull request by bisakhmondal**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
resolves #1555 

### New feature or improvement

https://user-images.githubusercontent.com/41498427/111036505-84c45000-8445-11eb-924f-bf013682becd.mp4

Thank You.

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]
LGTM

**Review by LiteSun — APPROVED** [review]

**Review by liuxiran — COMMENTED** [review]
LGTM for the code , it would be better to add test case for this nice new feature

**Review by LiteSun — APPROVED** [review]

**Comment by bisakhmondal** [comment]
> LGTM for the code , it would be better to add test case for this nice new feature

Thanks. Yeah, it's a nice but really minor addition to the codebase. Hey guys what do you think?

**Comment by juzhiyuan** [comment]
> > LGTM for the code , it would be better to add test case for this nice new feature
> 
> Thanks. Yeah, it's a nice but really minor addition to the codebase. Hey guys what do you think?

Agree :) Not urgent IMO.

**Review by LiteSun — APPROVED** [review]

**Review by liuxiran — APPROVED** [review]
> Thanks. Yeah, it's a nice but really minor addition to the codebase. Hey guys what do you think?

A single step makes a thousand miles ^_^
Adding test cases later is also a good option

**Review by bzp2010 — APPROVED** [review]

**Pull request merged**
