### PR TITLE
docs: update some tips in develop.md

### LINKED ISSUE #2427: [doc] How about adding a line in the dev-doc to prompt developers to ignore the error about node-gyp?
# Feature request

## Please describe your feature

Can we add a line under the following code to promote developers to ignore the error about node-gyp?
```
yarn install
yarn start
```

I am a newbie about apisix/apisix-dashboard. It took me **half a day** to consider why there was a error in the process of `yarn install`, and I found the result in [here](https://github.com/apache/apisix-dashboard/issues/702#issuecomment-722796795)

## Describe the solution you'd like

before:
```
yarn install
yarn start
```

after
```
yarn install
yarn start
```
> If there is an error about gyp during yarn install, please ignore it and go ahead!

### PR DESCRIPTION
**Pull request by gymgym1212**
Signed-off-by: Yeming Gu <yeminggood@gmail.com>

Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [ ] New feature provided
- [X] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Add some tips into `develop.md` to improve comprehensibility.

- advise to change the `make-api` address explicitly. Otherwise, an `403 forbidden` error will be generated when logging in, because the API address cannot be found.
- prompt the user to ignore gyp errors during `yarn install`

**Related issues**

fix/resolve #2427 

**Checklist:**

- [X] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [X] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]

**Review by membphis — APPROVED** [review]
LGTM, and @gymgym1212 pls fix the ci, it failed

**Comment by gymgym1212** [comment]
> LGTM, and @gymgym1212 pls fix the ci, it failed

Got it. I will fix the ci.

**Comment by gymgym1212** [comment]
"First-time contributors need a maintainer to approve running workflows."

**Comment by gymgym1212** [comment]
> "First-time contributors need a maintainer to approve running workflows."

Hi @juzhiyuan , can you approve these workflows?

**Pull request merged**
