### PR TITLE
chore: update setup script for e2e tests (ginkgo)

### PR DESCRIPTION
**Pull request by bisakhmondal**
Please answer these questions before submitting a pull request, **or your PR will get closed**.
This script was created to aid the developers with the environment and config required for testing e2e tests on ginkgo suite locally. This script was not maintained for a long time. So it is updated accordingly and made it work again.
image

image

**Why submit this pull request?**

- [ ] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [x] Backport patches

**What changes will this PR take into?**

Please update this section with detailed description.

**Related issues**

fix/resolve #0001

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by juzhiyuan** [comment]
Hi @bisakhmondal, not sure why that CI failed, may rerun that CI?

**Comment by juzhiyuan** [comment]
image

failed due to unstable test, but I cannot help to rerun this testcase 🤔 ping @bisakhmondal

**Comment by bisakhmondal** [comment]
> failed due to unstable test, but I cannot help to rerun this testcase thinking ping @bisakhmondal

Hi, thank you. Since the last run is more than 30days old, just pushed a blank commit : )

**Comment by bisakhmondal** [comment]
@juzhiyuan ci fixed.

https://github.com/apache/apisix-dashboard/pull/2204/checks?check_run_id=4682515670

I think we need to address these high priority issues.

**Comment by juzhiyuan** [comment]
> 

Ya, I have communicated with @zaunist, he will help to resolve them :)

**Comment by juzhiyuan** [comment]
cc @zaunist @nic-chen to have a review, thanks!

**Comment by zaunist** [comment]
> > 
> 
> Ya, I have communicated with @zaunist, he will help to resolve them :)

Thanks，I will check this issue when I have free time.

**Review by nic-chen — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Review by zaunist — APPROVED** [review]
I think this [check](https://github.com/apache/apisix-dashboard/pull/2204/checks?check_run_id=4682515670) is harmless. Here, the request data is written into the log. To use this log to do some bad things, people need to do it with other system vulnerabilities.

**Comment by juzhiyuan** [comment]
> I think this [check](https://github.com/apache/apisix-dashboard/pull/2204/checks?check_run_id=4682515670) is harmless. Here, the request data is written into the log. To use this log to do some bad things, people need to do it with other system vulnerabilities.

ok, cc @nic-chen and @bzp2010 .

**Review by bzp2010 — APPROVED** [review]

**Pull request merged**
