### PR TITLE
fix: sync the preload packages in schema-sync.lua 

### LINKED ISSUE #1216: bug: module 'resty.radixtree' not found when call command `http://schema-sync.sh/`
original comment: https://github.com/api7/lua-resty-radixtree/issues/87

ping @qwxingzhe

### PR DESCRIPTION
**Pull request by starsz**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

fix #1216 
___
### Bugfix
- Description

If the package used in apisix and not preload in schema-sync.lua.It will break down.

- How to fix?

Preload the package used in apisix.
___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by starsz** [comment]
Hi, @juzhiyuan. Help me look at the CI.

**Review by juzhiyuan — APPROVED** [review]

**Review by tokers — APPROVED** [review]

**Comment by imjoey** [comment]
@juzhiyuan  Just a reminder, since https://github.com/apache/apisix-dashboard/issues/1216#issuecomment-754686778 , please check if this PR needs backport to v2.3.

**Comment by juzhiyuan** [comment]
yes!

**Comment by imjoey** [comment]
> yes!

@juzhiyuan OK, please let me backport this.

BTW, the label attached should be `need_backport` instead of `backport`. 😄

**Pull request merged**
