### PR TITLE
chore: add loading in route page 

### LINKED ISSUE #2222: support Request Loading status
### Issue description

Delete route in apisix dashboard is not work.
image

once deleted is dose not work, but twice I got this error.

### Expected behavior

When I delete the route, the list of this route should not be in the list.

### How to Reproduce

just start the dashboard and delete the route.

### Screenshots

_No response_

### Environment

- apisix version (cmd: `apisix version`):2.5
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by CP3cham**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [ ] New feature provided
- [x] Improve performance
- [ ] Backport patches

**Related issues**

fix/resolve #2222 

**Checklist:**

add loading status in route page when the Internet is slow

>

### CODE REVIEW

**Comment by juzhiyuan** [comment]
cc @guoqqqi to have a review

**Comment by guoqqqi** [comment]
please add the test

**Comment by guoqqqi** [comment]
@CP3cham  ping
Did you have any problems?

**Review by zaunist — APPROVED** [review]
LGTM

**Review by guoqqqi — APPROVED** [review]
LGTM! Thank you for your contribution

**Review by 1502shivam-singh — APPROVED** [review]

**Review by LiteSun — APPROVED** [review]

**Review by bzp2010 — APPROVED** [review]

**Pull request merged**
