### PR TITLE
fix: fix the uptime translation error

### LINKED ISSUE #1596: Translation error
# Bug report

## Describe the bug
Hi all
I found when I switch the language to the **English** on some page and element still used the **Chinese**

## How to Reproduce

1. Go to Route List
2. See the error

## Screenshots
- Route List
image
image

Add screenshots to help explain your problem if applicable.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [e.g. 2.0-rc3]

## Additional context
If it is a bug, I would like to solve it.

### PR DESCRIPTION
**Pull request by stu01509**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues 
Fix #1596

___
### Bugfix
 Fix the uptime translation error in English mode.

- How to fix?
Add moment locale.

English Mode:
image

Chinese Mode:
image

### CODE REVIEW

**Comment by juzhiyuan** [comment]
cc @guoqqqi to guide how to fix this test

**Comment by guoqqqi** [comment]
OK, Let me check it.

**Comment by guoqqqi** [comment]
Hi, When you have time, please update the master code to fix the error.

**Comment by stu01509** [comment]
Hi @guoqqqi 

Update the commit

**Comment by stu01509** [comment]
Hi @juzhiyuan and @guoqqqi 

Seems like this PR passed the CI, Please review it 😀

**Review by juzhiyuan — APPROVED** [review]

**Review by liuxiran — APPROVED** [review]

**Review by guoqqqi — APPROVED** [review]

**Review by Jaycean — APPROVED** [review]

**Review by nic-chen — APPROVED** [review]

**Comment by juzhiyuan** [comment]
@stu01509 Hi, please sync latest codes.

**Comment by stu01509** [comment]
> @stu01509 Hi, please sync latest codes.

Done 😀

**Pull request merged**
