### PR TITLE
fix: modify the rpm link for 2.4

### LINKED ISSUE #1496: Broken RPM download link
@liuxiran Hi, this link is broken, please take a look.

_Originally posted by @juzhiyuan in https://github.com/apache/apisix-dashboard/pull/1489#r580121249_

### PR DESCRIPTION
**Pull request by liuxiran**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix

- Related issues
fix #1496

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]

**Review by bzp2010 — APPROVED** [review]
LGTM
😁

**Comment by juzhiyuan** [comment]
Need update v2.4 too :)

**Comment by liuxiran** [comment]
> Need update v2.4 too :)

Sorry for taking so long to notice this information.
I noticed that branch V2.4 has already been removed together with other released version branches, I just want to make sure that we don't maintain these branches until it becomes a LTS version right? @juzhiyuan

**Comment by juzhiyuan** [comment]
image

Hi, could you have a recheck?

**Comment by liuxiran** [comment]
> image
> 
> Hi, could you have a recheck?

Found it, it is not fully displayed on my phone, sorry.

**Pull request merged**
