### PR TITLE
fix: fix the button margin space

### LINKED ISSUE #1602: There have 2 buttons fit very close together
# Bug report

## Describe the bug

Hi, I notice that here have 2 buttons that fit very close together on the Upstream List page, they are the `View` & `Delete` buttons.

We need to add a gap between them.

image

### PR DESCRIPTION
**Pull request by stu01509**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues 
Fix #1602 

___
### Bugfix
- Description
Use and `Space` to add each button's margin, and remove inline margin style.

image

### CODE REVIEW

**Comment by juzhiyuan** [comment]
also cc @guoqqqi to take a look

**Comment by guoqqqi** [comment]
wait for #1608

**Review by juzhiyuan — APPROVED** [review]

**Review by guoqqqi — APPROVED** [review]

**Review by liuxiran — COMMENTED** [review]
LGTM expect a small detail:

It would be better to remove root dom `<></>`(https://github.com/apache/apisix-dashboard/pull/1604/files#diff-157cae0de0314d396c74fbb89c3f87b9b9c503826a29b3452e80d66a36a37120R63 and https://github.com/apache/apisix-dashboard/pull/1604/files#diff-157cae0de0314d396c74fbb89c3f87b9b9c503826a29b3452e80d66a36a37120R96), for `<Space></Space>` has already wrapped all the buttons.

**Comment by stu01509** [comment]
Hi @liuxiran 

Update the commit.

**Comment by liuxiran** [comment]
> Hi @liuxiran
> 
> Update the commit.

LGTM, be ci errors have been solved by #1638 , please try to update master to soluve it, thanks @stu01509

**Review by liuxiran — APPROVED** [review]

**Review by LiteSun — APPROVED** [review]

**Review by nic-chen — APPROVED** [review]

**Pull request merged**
