### PR TITLE
feat(Makefile): update release-src

### PR DESCRIPTION
**Pull request by LiteSun**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance

- Related issues

___
### Bugfix
- Description

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

### CODE REVIEW

**Comment by moonming** [comment]
@nic-chen please check the CI

**Comment by moonming** [comment]
I’m not sure if the installation document needs to be modified because the format of the package has changed

**Review by juzhiyuan — APPROVED** [review]
Looks good to me IMO, after improving makrfile, we don't need the removed part any more. 

But please make sure which environment could this command run.

**Comment by juzhiyuan** [comment]
CI failed doesn't due to this PR, and commands LGTM, so I just approved it.

**Comment by LiteSun** [comment]
> I’m not sure if the installation document needs to be modified because the format of the package has changed

Thanks for the reminder. I'll check that.

**Review by moonming — APPROVED** [review]

**Comment by moonming** [comment]
please release the new version ASAP

**Pull request merged**
