### PR TITLE
docs: add correct custom IDs to links 

### PR DESCRIPTION
**Pull request by KishaniKandasamy**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [X] Bugfix

**What changes will this PR take into?**
fix: #1806

### CODE REVIEW

**Comment by nic-chen** [comment]
hi @KishaniKandasamy  
I am updating api doc and that will be a big update. 
I think we don't need to update this file now.

**Comment by KishaniKandasamy** [comment]
> hi @KishaniKandasamy
> I am updating api doc and that will be a big update.
> I think we don't need to update this file now.

Okay:)

**Comment by starsz** [comment]
> > hi @KishaniKandasamy
> > I am updating api doc and that will be a big update.
> > I think we don't need to update this file now.
> 
> Okay:)

So we can close this PR. cc @nic-chen

**Comment by nic-chen** [comment]
closing. thanks @KishaniKandasamy

**Pull request closed without merging**
