### PR TITLE
feat(plugin): allowing basic-auth to dynamically adapt to the BE rules

### LINKED ISSUE #1588: Optimize front-end validation of fields
## The current front-end approach
To create a route for example, the front-end will be regular [1] check for certain fields, such as name field, if the regular condition is not met, the front-end page will report an error and block the user's next operation.

image

## The disadvantages of the current approach
The current front-end can meet the verification requirements. However, when the back-end changes the verification rules, the front-end has to passively and manually update the verification rules for the corresponding fields. If the back-end does not notify the front-end in time or misses some fields, then the synchronization of the front-end and back-end verification will be a problem, affecting the user's use.

## Improvement measures
After communicating with @membphis , using jsonschema validation would be a good choice.
The front-end calls the API to get the jsonschema of the corresponding module and then maps the corresponding jsonschema rules to the corresponding field checks on the front-end. Do this when the back-end update the validation rules, the front-end can automatically synchronize the latest validation rules, reducing unnecessary development time of the front-end.

[1] regular expressions provided by the back-end, and then manually added by the front-end developers to the corresponding form form for the field validation

cc @juzhiyuan @liuxiran @guoqqqi

### PR DESCRIPTION
**Pull request by wmdmomo**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [x] New feature provided
- [x] Improve performance
- [x] Backport patches

**What changes will this PR take into?**
The PR will change the plugin under plugin/UI (baic-auth), allowing baic-auth to dynamically adapt to the back-end json rules.

Please update this section with detailed description.

**Related issues**

fix/resolve #1588 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [x] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by liuxiran** [comment]
cool, LGTM from code, thanks @wmdmomo 
As you will see from our past exchanges, test cases are important for a pr, a test case about: enable `basic-auth` plugin in consumer, check whether the username and password are required form field . This will help us merge your pr smoothly.

Hope this example can help you: https://github.com/apache/apisix-dashboard/blob/master/web/cypress/integration/route/check-route-required-field-flag.spec.js

**Comment by liuxiran** [comment]
HI @wmdmomo any updates ? any problem can comment here, thanks a lot

**Comment by wmdmomo** [comment]
> HI @wmdmomo any updates ? any problem can comment here, thanks a lot
@liuxiran  Sorry to reply now. The basic-auth test case has been completed.

**Comment by wmdmomo** [comment]
@liuxiran Sorry to reply now. The basic-auth test case has been completed.

**Comment by bzp2010** [comment]
The code looks good to me. But please pay attention to the errors in CI.

**Comment by wmdmomo** [comment]
> @wmdmomo The code looks good to me. But please pay attention to the errors in CI.

@bzp2010  Thanks for your suggestion. I have modified it.

**Review by bzp2010 — APPROVED** [review]

**Comment by bzp2010** [comment]
> > @wmdmomo The code looks good to me. But please pay attention to the errors in CI.
> 
> @bzp2010 Thanks for your suggestion. I have modified it.

Nice jobs!

**Review by juzhiyuan — APPROVED** [review]

**Comment by bzp2010** [comment]
cc @liuxiran , please have a look.

**Review by iamayushdas — APPROVED** [review]

**Review by liuxiran — APPROVED** [review]
LGTM, thanks @wmdmomo

**Pull request merged**
