### PR TITLE
fix(be): push pr ci failed

### PR DESCRIPTION
**Pull request by Jaycean**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
#1401
___
### Bugfix
- Description
[Failed installing dependency,Could not find header file for OPENSSL](https://github.com/apache/apisix-dashboard/runs/1804604649)
- How to fix?
Dockerfile-apisix adds the specified OpenSSL library address.

### CODE REVIEW

**Comment by liuxiran** [comment]
Do we have a way to reuse apisix docker file in `apisix-docker` repo instead of a separate file in dashboard?

**Comment by Fuchange** [comment]
> Do we have a way to reuse apisix docker file in `apisix-docker` repo instead of a separate file in dashboard?

Yes,  we can use 
`https://github.com/apache/apisix-docker/raw/master/all-in-one/apisix/Dockerfile`
`https://github.com/apache/apisix-docker/raw/master/all-in-one/apisix-dashboard/Dockerfile`

to replace the existing local dockerfile

**Comment by Jaycean** [comment]
@liuxiran @Fuchange IMO, it is better to use a unified file, which is convenient for maintenance.Today's problem will appear if you maintain the Dockerfile of APISIX in the dashboard. The modification of APISIX does not synchronize with the update, resulting in errors.

**Comment by Jaycean** [comment]
ping @starsz @nic-chen @imjoey @tokers for review. Thks.

**Comment by liuxiran** [comment]
> > Do we have a way to reuse apisix docker file in `apisix-docker` repo instead of a separate file in dashboard?
> 
> Yes, we can use
> `https://github.com/apache/apisix-docker/raw/master/all-in-one/apisix/Dockerfile`
> `https://github.com/apache/apisix-docker/raw/master/all-in-one/apisix-dashboard/Dockerfile`
> 
> to replace the existing local dockerfile

Sound cool @Fuchange , maybe we can open a new issue to discuess this feature, thanks

**Comment by liuxiran** [comment]
an unstable fe test case , re-run, I opened an issue https://github.com/apache/apisix-dashboard/pull/1409/checks?check_run_id=1805078346 to trace it

**Review by imjoey — APPROVED** [review]
/lgtm

Thanks @Jaycean . So happy to see Backend E2E Testing passed. 🎉

**Review by nic-chen — APPROVED** [review]

**Review by starsz — APPROVED** [review]

**Pull request merged**
