### PR TITLE
feat(docs): update deploy

### LINKED ISSUE #843: docs: remind users to use correct way to run `manager api` in background
remind users that should use 

```sh
$ nohup ./manager-api &
``` 

instead of 

```sh
$ ./manager-api &
``` 
to run `manager api`, otherwise it will automatically exit after the terminal closed。

### PR DESCRIPTION
**Pull request by juzhiyuan**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

resolve #843

### CODE REVIEW

**Review by nic-chen — APPROVED** [review]

**Comment by moonming** [comment]
why the CI not run test cases of golang？

**Comment by juzhiyuan** [comment]
Because actions only detect master and 2.0? cc @nic-chen

**Comment by nic-chen** [comment]
> Because actions only detect master and 2.0? cc @nic-chen

yes.
I think we could enable actions for all release branches.

**Comment by juzhiyuan** [comment]
> why the CI not run test cases of golang？

related PR https://github.com/apache/apisix-dashboard/pull/846

I will merge this one bcz only docs are changed.

**Pull request merged**
