### PR TITLE
fix(be): Modify the service to use the new JSON patch package

### PR DESCRIPTION
**Pull request by Jaycean**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
#1392 
___
### Bugfix
- Description
I find that the jsonpatch(github.com/api7/go-jsonpatch) used by upstream and service when calling the patch method is still the old package,updated to github.com/evanphx/json-patch/v5

- How to fix?
Modify the service to use the new JSON patch package

### CODE REVIEW

**Comment by imjoey** [comment]
@Jaycean In order to be a semantic pull request, please change the title to `fix: Modify the service to use the new JSON patch package` . Thanks.

**Comment by Jaycean** [comment]
> @Jaycean In order to be a semantic pull request, please change the title to `fix: Modify the service to use the new JSON patch package` . Thanks.
OK, thank you for reminding me.

**Review by membphis — APPROVED** [review]

**Review by imjoey — APPROVED** [review]
/lgtm

@Jaycean nice work. Thanks.

**Comment by imjoey** [comment]
@Jaycean The CI check **Semantic Pull Request** failed due to the only commit is not semantic. That means your commit message should also starts with `fix`, and etc, the eligible phrase is defined at https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json. Regarding to this PR, the commit message should be `fix(be): Modify the service to use the new JSON patch package` instead of `Modify the service to use the new JSON patch package`.

Please avoid similar commit message next time and I think we could go on to merge this PR. 😄 

 @membphis @juzhiyuan  what's your opinions? Thanks.

**Comment by juzhiyuan** [comment]
This check is optional and could configure it to allow only one commit haha

**Review by nic-chen — APPROVED** [review]

**Comment by juzhiyuan** [comment]
Yep, it should be more semantic if possible:)

**Comment by imjoey** [comment]
> This check is optional and could configure it to allow only one commit haha

@juzhiyuan I guess we could explicitly specify an semantic.yml for customizations, just like `apache/apisix` project. I would commit an PR for this.

**Comment by juzhiyuan** [comment]
Could we set it Good first issue 😃

**Comment by imjoey** [comment]
> Yep, it should be more semantic if possible:)

@juzhiyuan @nic-chen OK, thanks. So let me merge this

> Could we set it Good first issue 😃

Sure, I would commit an issue and set it as Good-first 😄 .

**Comment by imjoey** [comment]
At squash and merge, I change the commit message and make it semantic. 👻

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-dashboard/runs/1795823653

Hi @Jaycean , CI failed after being merged into the master branch.

**Comment by imjoey** [comment]
> https://github.com/apache/apisix-dashboard/runs/1795823653
> 
> Hi @Jaycean , CI failed after being merged into the master branch.

@juzhiyuan yep. CI checks for this PR was fine, so I merged the commit, but CI failed for `push` the commit. I'm afraid that I did not get any relationship between the CI failure and the changes in this PR. CI failed at the very beginning phase of running `balancer_test`, which I think would not be introduced by this PR. Any ideas? Thanks.

**Comment by juzhiyuan** [comment]
fine, I don't mean CI failed due to this PR 😂 just saw after PR merged, CI down.

image

Let me create an issue to track this.

**Comment by Jaycean** [comment]
> fine, I don't mean CI failed due to this PR 😂 just saw after PR merged, CI down.
> 
> image
> 
> Let me create an issue to track this.

Yes, but both my CI last night and my local CI passed successfully. Let me check the reasons

**Comment by imjoey** [comment]
@juzhiyuan @Jaycean The `balancer_test` is passed in my local e2e testing. Could you please have a try locally? I proposed a  PR to revert this commit at #1400 , it also fails. 😢

**Comment by juzhiyuan** [comment]
No need to revert this PR IMO because it doesn't make the CI failed, as far as I know, I just created an issue to track this.

https://github.com/apache/apisix-dashboard/issues/1401

**Pull request merged**
