### PR TITLE
fix: change "Route List" to "Routes"

### LINKED ISSUE #2387: bug: i18n improvements
### Issue description

Catch all issue to improve i18n:

- [ ] Replace Route List with Routes
- [ ] Use a shorter label for Title and Description

### PR DESCRIPTION
**Pull request by gymgym1212**
Signed-off-by: Yeming Gu <yeminggood@gmail.com>

Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [x] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Replace `Route List` with `Routes`.

But I'm not sure whether it's enough or not. 

**Related issues**

fix/resolve #2387 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by Baoyuantop** [comment]
Need to fix a failed front-end E2E, feel free to leave a message if you need help.

**Comment by gymgym1212** [comment]
Hi @Baoyuantop, I'm wondering if the ci error is caused by the dev serveUrlMap
https://github.com/apache/apisix-dashboard/blob/227b2000296a2665dd7cac31f8671b1d34672612/web/config/defaultSettings.ts#L34-L37

In my MacBook, I will get this error:
```
[HPM] Error occurred while trying to proxy request /apisix/admin/labels/route from localhost:8000 to http://139.217.190.60 (ETIMEDOUT) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /apisix/admin/routes?label=&page=1&page_size=10 from localhost:8000 to http://139.217.190.60 (ETIMEDOUT) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

And the Route List is always in `loading` state, like below:
image

Therefore, this may lead to the error that the corresponding element cannot be obtained.
image

**Comment by gymgym1212** [comment]
Sry, I found the e2e is running under test SERVE_ENV.

**Comment by gymgym1212** [comment]
I did the e2e test `yarn test:e2e` on my local environment. But I still got the error. Why is the dev serveUrlMap used instead of test serveUrlMap? @Baoyuantop Can you figure it out?
```
[HPM] Error occurred while trying to proxy request /apisix/admin/plugin_configs from localhost:8000  
 to http://139.217.190.60 (ETIMEDOUT) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /apisix/admin/plugins?all=true from localhost:8000 to  
http://139.217.190.60 (ETIMEDOUT) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /apisix/admin/plugin_configs from localhost:8000 to  
http://139.217.190.60 (ETIMEDOUT) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by gymgym1212** [comment]
> I did the e2e test `yarn test:e2e` on my local environment. But I still got the error. Why is the dev serveUrlMap used instead of test serveUrlMap? @Baoyuantop Can you figure it out?
> 
> ```
> [HPM] Error occurred while trying to proxy request /apisix/admin/plugin_configs from localhost:8000  
>  to http://139.217.190.60 (ETIMEDOUT) (https://nodejs.org/api/errors.html#errors_common_system_errors)
> [HPM] Error occurred while trying to proxy request /apisix/admin/plugins?all=true from localhost:8000 to  
> http://139.217.190.60 (ETIMEDOUT) (https://nodejs.org/api/errors.html#errors_common_system_errors)
> [HPM] Error occurred while trying to proxy request /apisix/admin/plugin_configs from localhost:8000 to  
> http://139.217.190.60 (ETIMEDOUT) (https://nodejs.org/api/errors.html#errors_common_system_errors)
> ```

My fault again... I created two front-end parts.

**Comment by gymgym1212** [comment]
Hi @Baoyuantop , I create a `test` branch in my forked repo and **the ci passed all the test**. The only difference is that I changed the action trigger branch from master to test....

https://github.com/gymgym1212/apisix-dashboard/runs/6541608647?check_suite_focus=true

I'm very confused about the inconsistent results. Can you help me analyze the reasons？

**Comment by Baoyuantop** [comment]
Ok, maybe the test code is not stable enough, let me retrigger it

**Review by Baoyuantop — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Comment by Baoyuantop** [comment]
cc @guoqqqi

**Review by guoqqqi — APPROVED** [review]

**Pull request merged**
