### PR TITLE
feat: add file server

### PR DESCRIPTION
**Pull request by ShiningRush**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance

___
### New feature or improvement
Add file server for manager api,if we want embed web files to go, we can do it in next version(before do it, please have a look at [Choosing A Library to Embed Static Assets in Go](https://tech.townsourced.com/post/embedding-static-files-in-go/)).
Next I think we still have a few things to do:
1. Change the project structure to make web's folder and managerapi's folder in root
2. Add Makefile to the root directory, we can run it to make a binary and dist
3. Modify the dockerfile of manager api , remove the compilation stage, and build it directly in CI

### CODE REVIEW

**Comment by juzhiyuan** [comment]
ok https://github.com/apache/apisix-dashboard/issues/593

**Comment by juzhiyuan** [comment]
Could you please add some docs about how to use this way?

https://github.com/apache/apisix-dashboard#deployment

**Comment by juzhiyuan** [comment]
and how about this PR? https://github.com/apache/apisix-dashboard/pull/588

**Review by gxthrj — APPROVED** [review]

**Comment by nic-chen** [comment]
@ShiningRush  I think we should add doc about how to deploy manually with this file server.

**Review by bzp2010 — APPROVED** [review]

**Review by nic-chen — APPROVED** [review]

**Comment by membphis** [comment]
we merge it ^_^

**Pull request merged**
