### PR TITLE
chore: sync JSON Schema from APISIX version 2.3

### PR DESCRIPTION
**Pull request by nic-chen**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

 sync JSON Schema from APISIX version 2.3

### CODE REVIEW

**Review by tokers — APPROVED** [review]

**Comment by membphis** [comment]
frontend e2e failed

**Comment by membphis** [comment]
ping @LiteSun

**Review by juzhiyuan — APPROVED** [review]

**Review by starsz — APPROVED** [review]

**Comment by LiteSun** [comment]
The reason why the front-end e2e hangs is because the authz-keycloak schema is updated, the front-end needs to update the test data of the authz-keycloak plugin. will fix it soon.

image

**Comment by imjoey** [comment]
@juzhiyuan @starsz  This PR needs to be backported to v2.4 branch for release 2.4.

**Pull request merged**
