### PR TITLE
feat: release 2.10.0

### PR DESCRIPTION
**Pull request by okaybase**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**
Release version 2.10.0, after this version released, APISIX Dashboard can work together with APISIX 2.11.0. There may be a lack of functionality.

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [x] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]

**Comment by juzhiyuan** [comment]
LGTM and let's wait for the VOTE.

**Review by 1502shivam-singh — APPROVED** [review]

**Review by TakumiInui5432 — APPROVED** [review]

**Review by bzp2010 — APPROVED** [review]

**Comment by belongwqz** [comment]
the rpm file need to upload

**Comment by zaunist** [comment]
cc @juzhiyuan

**Comment by juzhiyuan** [comment]
Hi @belongwqz @zaunist, @bzp2010 is working on RPM/Docker/Helm Chart. Will upload them to registry once done.

**Pull request merged**
