### PR TITLE
feat: improve codes style & bug fix

### LINKED ISSUE #527: wolf-rbac can't add to plugin page
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
why wolf-rbac can't add to plugin page?

This is the reference document for me: https://github.com/iGeeky/apisix-plugin-rbac

I'm sure I've moved the wolf-rbac.lua to the right place
I try to add it in config.yaml and config.default.yaml, all failed!

截屏2020-09-29 下午7 58 26

I find the array returned by backend API has wolf-rbac, but the consumer page is not displayed

截屏2020-09-29 下午8 08 05

However,  the route management page display it in the drag plugin

截屏2020-09-29 下午8 16 23

I wonder if there are configuration files in the frontend, but i can't find it. Is there any other way? Or is it only used by backend API?

### PR DESCRIPTION
**Pull request by juzhiyuan**
- [x] Update Request intercepters
- [x] remove unused codes
- [x] fix plugin
- [x] hide SSL module

resolve #527

### CODE REVIEW

**Review by LiteSun — APPROVED** [review]
LGTM!

**Comment by liuxiran** [comment]
may I ask why hide ssl module?

**Comment by juzhiyuan** [comment]
> may I ask why hide ssl module?

Because there has one API which doesn't support PATCH SSL (enable or disable)

**Comment by juzhiyuan** [comment]
> may I ask why hide ssl module?

SSL module will be updated and enabled in the 2.1 milestone.

**Review by liuxiran — APPROVED** [review]
LGTM

**Comment by liuxiran** [comment]
> SSL module will be updated and enabled in the 2.1 milestone.

Ok, thx

**Pull request merged**
