### PR TITLE
feat: update enabled_merge_buttons

### PR DESCRIPTION
**Pull request by juzhiyuan**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches
___
### New feature or improvement
- Describe the details and related test reports.

We only support Squash mode, but once we want to sync the master branch with another release branch, we have to cherry-pick one by one. It's useful to use Merge before releasing a branch.

### CODE REVIEW

**Comment by juzhiyuan** [comment]
Cherry pick one by one

**Comment by imjoey** [comment]
@juzhiyuan 

IMHO, the cherry-pick work will not cost too much time if we can keep the release cycle as short as possible, especially with a time plan. For example, once getting started for a new release, we could checkout a new release branch and froze features, as well as make the configurations and  CI ready for the release branch.

Then in the next few days, only bug fixes affected this release would be cherry picked from master branch. During this period, we should keep an eye on every single issue and PR to determine if it's related to the new release.

Honestly, I've no idea if there any specific release flow limit as an Apache project. So looking forward to your insights that I can learn a lot from you. Thanks.

**Comment by juzhiyuan** [comment]
You are right, and we should label every needed PRs that merged into master branch as need back port, clear for release manager as well.

**Comment by imjoey** [comment]
> You are right, and we should label every needed PRs that merged into master branch as need back port, clear for release manager as well.

yep, this practice is also very helpful for managing a LTS branch, alongside master branch. 😄

**Pull request closed without merging**
