### PR TITLE
feat: added github link to header #1632

### LINKED ISSUE #1632: improve some minor issues
Here are some minor issues on the Login page we could resolve.

## TODO
- [ ] Left icon replacement. @LiteSun 
- [ ] Extracting Table as a separate component for reuse in various modules.
- [ ] APISIX plugin type change.
- [ ] GitHub hyperlink (icon) added to Header section.

### PR DESCRIPTION
**Pull request by iamayushdas**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**
Github hyperlink(icon) added has been added to header section of login page
User will be directed to https://apisix.apache.org.

Please update this section with detailed description.
Github hyperlink(icon) has been added to header section of login page
User will be directed to https://apisix.apache.org.

fix/resolve #1632 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

screenshot of changes done 
@LiteSun @juzhiyuan 

screencapture-172-20-10-3-8000-user-login-2021-03-23-09_08_39

### CODE REVIEW

**Comment by iamayushdas** [comment]
CI not responding @juzhiyuan

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-dashboard/pull/1649

This PR will resolve backend CI

**Comment by iamayushdas** [comment]
> https://github.com/apache/apisix-dashboard/pull/1649
> 
> 
> 
> This PR will resolve backend CI

I added the google cloud container registry to the repo. I hope that won't be a issue?

**Comment by nic-chen** [comment]
> I added the google cloud container registry to the repo as stated in #1649. I hope that won't be a issue?

#1649 has been merged, please sync codes from branch master

**Comment by iamayushdas** [comment]
> > I added the google cloud container registry to the repo as stated in #1649. I hope that won't be a issue?
> 
> 
> 
> #1649 has been merged, please sync codes from branch master

✅ okay

**Comment by iamayushdas** [comment]
> > > I added the google cloud container registry to the repo as stated in #1649. I hope that won't be a issue?
> > 
> > 
> > #1649 has been merged, please sync codes from branch master
> 
>  okay

done

**Review by juzhiyuan — APPROVED** [review]
also cc @nic-chen to review

**Review by nic-chen — APPROVED** [review]

**Comment by iamayushdas** [comment]
need two more approvals @juzhiyuan

**Review by Jaycean — APPROVED** [review]

**Review by liuxiran — APPROVED** [review]

**Pull request merged**
