### PR TITLE
feat: basic support Apache APISIX 2.12.1

### PR DESCRIPTION
**Pull request by Baoyuantop**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Adapt Apache APISIX version 2.12.1, synchronize schema to support new plugins.

**Related issues**

follow: https://github.com/apache/apisix/pull/6254

**Checklist:**

- [ ] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by zaunist** [comment]
Please fix the CI.

**Review by zaunist — APPROVED** [review]

**Comment by Baoyuantop** [comment]
cc @bzp2010

**Comment by Baoyuantop** [comment]
Anything else?

**Review by bzp2010 — APPROVED** [review]

**Comment by Baoyuantop** [comment]
cc @juzhiyuan @LiteSun

**Review by juzhiyuan — APPROVED** [review]

**Review by LiteSun — APPROVED** [review]

**Pull request merged**
