### PR TITLE
fix: (route_online_debug)Change the appended Content-type data to overlay to ensure that the Content-type is unique

### PR DESCRIPTION
**Pull request by Jaycean**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues

___
### Bugfix
- Description
There is a bug in the use process. The user writes the `Content-type` to the `header-params` to forward the content type of the URL. The old logic uses the `req.Header.Add` method to generate multiple `Content-type` values, which leads to the failure of the forwarding request.

- How to fix?
use `req.Header.Set` To override the ·Content-type· and ensure that the value is unique。

### CODE REVIEW

**Comment by liuxiran** [comment]
related fe pr: #1612

**Review by nic-chen — APPROVED** [review]
LGTM

**Review by membphis — APPROVED** [review]

**Comment by Jaycean** [comment]
cc @liuxiran @LiteSun @juzhiyuan FE CI Failed PTAL. Thks.

**Comment by liuxiran** [comment]
mark fe e2e errors:
* search route error: https://github.com/apache/apisix-dashboard/pull/1619/checks?check_run_id=2146696140
* create-edit-delete consumer error: https://github.com/apache/apisix-dashboard/pull/1619/checks?check_run_id=2150934899

**Review by liuxiran — APPROVED** [review]
fe local test passed, LGTM

**Review by starsz — APPROVED** [review]

**Pull request merged**
