### PR TITLE
feat: set a initial weight value for the upstream node

### PR DESCRIPTION
**Pull request by okaybase**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**
For most scenarios, the weight value of the upstream node is 1, so setting a initial weight value 1 can reduce user input.

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Please update this section with detailed description.

**Related issues**

fix/resolve
image

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by iamayushdas** [comment]
@okaybase I don't think its the need right now, also doing break change to code directly will ruin the tests also

**Comment by okaybase** [comment]
Thanks for your review firstly. @iamayushdas 
Just like the initial value for connecting/sending/reading timeout, by setting a initial weight value for the upstream node, can reduce user input.

**Comment by juzhiyuan** [comment]
> Thanks for your review firstly. @iamayushdas
> Just like the initial value for connecting/sending/reading timeout, by setting a initial weight value for the upstream node, can reduce user input.

I'm not sure if this will take a break change for users 🤔 need @liuxiran and @nic-chen to confirm.

**Comment by nic-chen** [comment]
> > Thanks for your review firstly. @iamayushdas
> 
> > Just like the initial value for connecting/sending/reading timeout, by setting a initial weight value for the upstream node, can reduce user input.
> 
> 
> 
> I'm not sure if this will take a break change for users 🤔 need @liuxiran and @nic-chen to confirm.

If it fill in the default value automatically when weight is empty, I think it's ok.

**Comment by iamayushdas** [comment]
Okay then

**Comment by juzhiyuan** [comment]
so should we allow the default value 1? @nic-chen

**Comment by nic-chen** [comment]
> so should we allow the default value 1? @nic-chen

1 is OK. 

It’s just that if the weight is filled in by default, users may forget to change it in by themselves. I also hesitate about this.

**Comment by liuxiran** [comment]
> > Thanks for your review firstly. @iamayushdas
> > Just like the initial value for connecting/sending/reading timeout, by setting a initial weight value for the upstream node, can reduce user input.
> 
> I'm not sure if this will take a break change for users 🤔 need @liuxiran and @nic-chen to confirm.

I want to make sure that when there is only one node in the upstream, the value of the weight is of little significance right @nic-chen , and when there are several nodes in the upstream, the user would be an advanced user IMO, he/she would know how to set the wight.

So set default value for weight is good for me.

**Review by juzhiyuan — APPROVED** [review]

**Comment by okaybase** [comment]
Thanks for your review firstly. @juzhiyuan @nic-chen @liuxiran  

In a production environment, the number of upstream nodes is usually large in order to solve single-point problems and handle large request traffic.

**Review by iamayushdas — APPROVED** [review]

**Comment by okaybase** [comment]
Thanks for your approval. @juzhiyuan @iamayushdas

**Review by liuxiran — APPROVED** [review]

**Review by gxthrj — APPROVED** [review]

**Pull request merged**
