### PR TITLE
feat(route): show route id in list and edit views.

### LINKED ISSUE #1595: feat: Show route ID at LIST and EDIT views in dashboard
# Feature request

## Please describe your feature

follow this guide to  https://github.com/apache/apisix/blob/master/docs/en/latest/getting-started.md
to create a test route , the final route  is 
```
{
  "action": "get",
  "node": {
    "value": {
      "plugins": {
        "proxy-rewrite": {
          "scheme": "https",
          "regex_uri": ["^\/samplePrefix\/get(.*)", "\/get$1"]
        },
        "key-auth": {}
      },
      "id": "5",
      "uri": "\/samplePrefix\/get",
      "update_time": 1615794114,
      "status": 1,
      "upstream_id": 50,
      "priority": 0,
      "create_time": 1615793637
    },
    "key": "\/apisix\/routes\/5"
  },
  "count": "1"
}

```
The id field is `id` which is 5 here, 
but when I open `dashboard`,  it use `name` as a required and primary key.  and there's no place to display `id` in the UI.
User can not  even go to the next step in the edit mode to see all the data
image
image

## add default name 
-  change logic in the PUT route api, set a default name from the url params if there's no name pass in the body
 - display id field in List.And Edit route view

### PR DESCRIPTION
**Pull request by mangoGoForward**
Signed-off-by: mango <xu.weiKyrie@foxmail.com>

Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Display route id at route list and edit views.

**Related issues**

fix/resolve #1595

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by mangoGoForward** [comment]
Please have a look. @juzhiyuan

**Review by juzhiyuan — COMMENTED** [review]
Hi @mangoGoForward, those changes LGTM, could you please add some test cases for this PR?

**Comment by juzhiyuan** [comment]
also cc @guoqqqi to have a review.

**Review by iamayushdas — APPROVED** [review]

**Review by iamayushdas — COMMENTED** [review]
just add the test cases as @juzhiyuan said, thanks @mangoGoForward

**Comment by zaunist** [comment]
Hi，@mangoGoForward. Can you take some screenshoot for this feature?

**Comment by mangoGoForward** [comment]
> just add the test cases as @juzhiyuan said, thanks @mangoGoForward

Ok.

**Comment by mangoGoForward** [comment]
> Hi @mangoGoForward, those changes LGTM, could you please add some test cases for this PR?

Thanks for your suggestion.

**Comment by guoqqqi** [comment]
LGTM, Hi @mangoGoForward, as we don't have a preview environment at the moment, it would be nice if we could post a picture up ~
If you have any questions about the test and need help.  just @ me～

**Comment by mangoGoForward** [comment]
The screenshot like below:
 List page
image

Edit page
image

**Review by zaunist — APPROVED** [review]

**Comment by mangoGoForward** [comment]
> LGTM, Hi @mangoGoForward, as we don't have a preview environment at the moment, it would be nice if we could post a picture up ~ If you have any questions about the test and need help. just @ me～

Sorry, I am confused about frontend e2e test of workflow errors, and how to support test cases for this PR. Could you help me to solved if you have free time?

**Comment by juzhiyuan** [comment]
After checking the codes and screenshots, these tiny changes look good to me, too. (Just adding ID & disabled attribute), I think we can move forward with this PR to merge 🤔

**Review by juzhiyuan — APPROVED** [review]

**Review by bzp2010 — APPROVED** [review]

**Comment by guoqqqi** [comment]
We can update this in the corresponding test for creating a route that
1. assert that there is an id field
2. the id is not clickable when editing

I think we can do this in another PR~

**Review by guoqqqi — APPROVED** [review]

**Comment by juzhiyuan** [comment]
Hi @guoqqqi, please have a check at the CI https://github.com/apache/apisix-dashboard/runs/4655853255?check_suite_focus=true

**Comment by guoqqqi** [comment]
> please have a check at the CI
just an unstable test
image
I will fix it in other PRs

**Comment by zaunist** [comment]
cc @okaybase @LiteSun

**Review by juzhiyuan — APPROVED** [review]

**Review by okaybase — APPROVED** [review]

**Pull request merged**
