### PR TITLE
feat: add upstream id in form

### LINKED ISSUE #2319: feat: Display ID of all objects on the dashboard
### Feature description

The Admin API allows to create objects (Route, Upstream, etc.). You can either set the ID or let APISIX generate one for you.

The dashboard doesn't show IDs, so in the case of auto-generated IDs, you need to first query the object and find the ID before using it as a reference. It would be more user-friendly to display the ID in the dashboard as a read-only field.

>As a User, I want to display IDs in the dashboard in order to reference them easily in other commands

### PR DESCRIPTION
**Pull request by zaunist**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

Add upstream id in form.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Please update this section with detailed description.

image

**Related issues**

fix #2319 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by zaunist** [comment]
Hi, @Baoyuantop @guoqqqi . Due to the ID is generated by manager-api, so I can't use the assert function to determine the value of the ID, so I can't add test cases. Could you give me some suggestions ?

**Comment by Baoyuantop** [comment]
Hi @zaunist, I think it is possible to determine whether the ID value of a column is displayed or not, as to how much the value is not concerned.

**Comment by guoqqqi** [comment]
Agree +1

**Comment by zaunist** [comment]
@bzp2010 @juzhiyuan @LiteSun @guoqqqi @Baoyuantop  PTAL

**Review by bzp2010 — APPROVED** [review]

**Review by LiteSun — APPROVED** [review]

**Review by guoqqqi — APPROVED** [review]

**Review by Baoyuantop — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
