### PR TITLE
release: new version 2.6

### PR DESCRIPTION
**Pull request by nic-chen**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

release version 2.6

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [x] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]

**Review by imjoey — APPROVED** [review]
/lgtm

**Review by liuxiran — APPROVED** [review]
LGTM

**Review by tokers — APPROVED** [review]

**Review by starsz — APPROVED** [review]

**Review by LiteSun — APPROVED** [review]

**Review by gxthrj — APPROVED** [review]

**Comment by bisakhmondal** [comment]
LGTM. Please update https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/deploy-with-rpm.md with v2.5's rpm binary link. Thanks.

**Comment by nic-chen** [comment]
@bisakhmondal  
Thanks for reminder. We could update it after upload the new version rpm.

**Comment by belongwqz** [comment]
Then where's rpm of 2.6?

**Comment by juzhiyuan** [comment]
@belongwqz Hi, it's here https://github.com/apache/apisix-dashboard/suites/2559506287/artifacts/55712524

Our CI build it automatically, @nic-chen please upload it to Release page :)

**Pull request merged**
