### PR TITLE
test: delete unnecessary wait in E2E

### LINKED ISSUE #1194: test:  Check for unnecessary wait in FE e2e
# Feature request
The current e2e test case [1] has many `cy.wait()` [2] statements, we cannot change the test code because of the host environment, we need to check if the statements are required, if they are not required, remove them.

refer links:
1: https://github.com/apache/apisix-dashboard/blob/master/web/cypress/integration/upstream/create_and_delete_upstream.spec.js#L73- L84
2: https://docs.cypress.io/guides/references/best-practices.html#Unnecessary-Waiting

### PR DESCRIPTION
**Pull request by guoqqqi**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
resolve #1194 
___
### New feature or improvement
- Describe the details and related test reports.
delete unnecessary wait in E2E 
NOTE: I will delete files one by one, one commit per file
___

### CODE REVIEW

**Comment by guoqqqi** [comment]
I will solve these failed tests one by one！

**Review by moonming — APPROVED** [review]

**Review by juzhiyuan — CHANGES_REQUESTED** [review]
Once you resolved all failed cases, then update here.

**Comment by guoqqqi** [comment]
This CI test failed, waiting for the PR https://github.com/apache/apisix-dashboard/pull/1364 merge to resolve

**Review by juzhiyuan — APPROVED** [review]

**Comment by LiteSun** [comment]
Good pr to remove the unnecessary `cy.wait()` 👍, but also to reduce the front-end e2e test time.

**Pull request merged**
