### PR TITLE
feat: rewrite e2e test(route-with-valid-remote-addr-test) with ginkgo

### PR DESCRIPTION
**Pull request by Jaycean**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
#1500

___
### New feature or improvement
-  Rewrite e2e test(route-with-valid-remote) with ginkgo

### CODE REVIEW

**Review by nic-chen — COMMENTED** [review]
Using `table.Entry` is better for us, and we could clearly see the comparison before and after the modification.

**Review by starsz — APPROVED** [review]

**Comment by Jaycean** [comment]
> Using `table.Entry` is better for us, and we could clearly see the comparison before and after the modification.

Here also need to create route and replace upstream_ id，`table.entry` There is no way to create a new variable.

**Comment by nic-chen** [comment]
> > Using `table.Entry` is better for us, and we could clearly see the comparison before and after the modification.
> 
> Here also need to create route and replace upstream_ id，`table.entry` There is no way to create a new variable.

the old test cases are all table driven

**Comment by Jaycean** [comment]
> > > Using `table.Entry` is better for us, and we could clearly see the comparison before and after the modification.
> > 
> > 
> > Here also need to create route and replace upstream_ id，`table.entry` There is no way to create a new variable.
> 
> the old test cases are all table driven

It's my problem. I'll revise it

**Review by nic-chen — APPROVED** [review]

**Comment by nic-chen** [comment]
merged. thanks a lot. @Jaycean

**Pull request merged**
