### PR TITLE
feat: use menu and menu item to wrap buttons

### LINKED ISSUE #1493: Support More selectors on List page
# Feature request

## Please describe your feature

Support More Actions selector on the List page, to prevent too many buttons.

image

### PR DESCRIPTION
**Pull request by stu01509**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
Fix #1493 
___
### Bugfix
- Description
Use the `Menu` and `Menu.Item` to wrap the **下线** 与 **删除** buttons.

image

image

- How to fix?

### CODE REVIEW

**Comment by juzhiyuan** [comment]
@guoqqqi Hi, please guide @stu01509 to fix the failed CI, thanks!

**Comment by guoqqqi** [comment]
Hi, The frontend e2e test failed because the position of the Delete button was changed. 
We can fix the error by replacing `cy.contains(this.data.routeName).siblings().contains('Delete').click();` with 
```
cy.contains('Manage').should('exist').click();
cy.contains('Delete').should('be.visible').click();
``` 
in all tests.
**This means that all route-related tests will need to be changed.**
very thanks!

**Comment by nic-chen** [comment]
wait for #1594

**Comment by nic-chen** [comment]
hi, please sync codes from branch master.

**Comment by guoqqqi** [comment]
Hi, @stu01509 The front-end tests on deleting routes all need to be updated, so if you encounter any problems, we can discuss them all here.
I have written an example for you about a for loop to delete route. You can refer to the official documentation: https://docs.cypress.io/api/api/table-of-contents.html
image
image

**Comment by guoqqqi** [comment]
Hi, @stu01509  here are some conflicting files that need to be updated.

**Pull request closed without merging**
