### PR TITLE
ci:  display more meaningful information when running E2E test cases failed

### LINKED ISSUE #911: feat(e2e): display more meaningful information when running E2E test cases fail
Here is the current output:

image

Need to show `caseDesc` field. 
Without it, we would not be able to quickly confirm which test case caused the failure.

It would be better if the original test case line number could be displayed.

### PR DESCRIPTION
**Pull request by nic-chen**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance

- Related issues

close #911

### CODE REVIEW

**Comment by membphis** [comment]
When the test case fails, what does the current prompt message look like?

**Comment by nic-chen** [comment]
> When the test case fails, what does the current prompt message look like?

Each test case prints its function name and `Desc`, like:

 ` TestRoute_With_Plugin_Proxy_Rewrite/make_sure_the_route_is_not_created` (`Desc` automatically adds `_`)

**Review by membphis — APPROVED** [review]
lgtm

**Comment by membphis** [comment]
ping @nic-chen

**Review by gxthrj — APPROVED** [review]
LGTM

**Pull request merged**
