### PR TITLE
feat: add store hub and flake id

### PR DESCRIPTION
**Pull request by ShiningRush**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bug fix
- [x] New feature provided
- [x] Improve performance

- Related issues
#466 
#519 

Changes:
- Now,we can refer multiple store in same handler by `storehub`, so we can use them to check key if existed or other situation.(plz have a look at route handler)
- Add `sonyflake` to generate id when client not specify id.
- Using interface to decouple `GenericStore`, so now we can do unit test for handler.

cc @nic-chen @moonming @membphis @juzhiyuan 

Happy National day~

### CODE REVIEW

**Comment by juzhiyuan** [comment]
I don't know much about Golang, so ping @nic-chen @gxthrj @bzp2010 here.

**Comment by ShiningRush** [comment]
Don't mind, you can see the pr as a notification that those issue have already resolved : )

**Review by juzhiyuan — APPROVED** [review]
Looks good to me from codes style

**Comment by juzhiyuan** [comment]
ping @moonming @nic-chen

**Review by moonming — APPROVED** [review]

**Review by nic-chen — APPROVED** [review]

**Pull request merged**
