### PR TITLE
chore: update the year in the  NOTICE

### LINKED ISSUE #2724: Update the year in the NOTICE file
# Feature request

## Please describe your feature

Update the year in the NOTICE file

### PR DESCRIPTION
**Pull request by Shivam0500**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- the year was wrongly mentioned 

**What changes will this PR take into?**

the year was wrongly mentioned in the notice

**Related issues**

fix #2724 

**Checklist:**

- [x] Have you modified the corresponding document?

### CODE REVIEW

**Review by Baoyuantop — APPROVED** [review]
Please fill in the PR description completely and change the PR title, you can manipulate other PRs.

**Comment by Shivam0500** [comment]
The Pr description has been changed and the description has been updated
fir the description I'm Complete beginner in the open source world 
hope you'll understand
Hoping to work with apache org 
thank you

**Review by SkyeYoung — APPROVED** [review]

**Comment by KID-G** [comment]
> The Pr description has been changed and the description has been updated fir the description I'm Complete beginner in the open source world hope you'll understand Hoping to work with apache org thank you

Hi, Tell me your email, the community thanks new contributors.

**Comment by Shivam0500** [comment]
hey sorry for late reply
my college exams were going on
my email is -> shivamaggarwal0005@gmail.com
and i am currently learning MERN stack development 
thank you

**Pull request merged**
