### PR TITLE
fix: incomplete label display #1044

### LINKED ISSUE #1044: bug: Incomplete label display when create rule in route step1 page
# Bug report

## Describe the bug

image

## How to Reproduce

1. Go to 'Create Route Page'
2. Click on 'Create' button below Advanced Routing Matching Conditions 

## Expected behavior

image

## Screenshots

Add screenshots to help explain your problem if applicable.

## System information

- OS: [macOS]
- Browser (if applies) [Chrome]

### PR DESCRIPTION
**Pull request by KishaniKandasamy**
- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
- fix #1044

___
### Bugfix
- Description
 Incomplete label display when create rule in route step1 page

- How to fix?
I have updated MatchingRulesView.tsx to make the Incomplete label display  as expected behavior when create rule in route step1 page

### CODE REVIEW

**Comment by juzhiyuan** [comment]
Hi @KishaniKandasamy, could you please take a screenshot of this modal? so we could know how does it look when using `vertical` :)

**Comment by KishaniKandasamy** [comment]
> Hi @KishaniKandasamy, could you please take a screenshot of this modal? so we could know how does it look when using `vertical` :)

Screenshot (8)

**Comment by juzhiyuan** [comment]
Oh! That looks good to me!

**Review by juzhiyuan — APPROVED** [review]

**Comment by juzhiyuan** [comment]
We may use `vertical` for other modals in the future.

**Review by LiteSun — APPROVED** [review]

**Pull request merged**
