### PR TITLE
fix: run lint-staged on whole project

### LINKED ISSUE #2035: lint-staged caused many additional changes
## Issue description
When committing some code changes in the `web`, `lint-staged` started and made many additional changes (regarding the code format), which caused a lot of trouble for the review code.

I noticed that this feature was added 15 days ago #1957, and the corresponding code format may be missing before then?

## Expected behavior
In a PR, `lint-staged` does not change the extra code

## How to Reproduce
Make code changes on the web, and then commit the code.

## Screenshots
image
https://github.com/apache/apisix-dashboard/pull/2034/files#diff-88ff6b2eb91bde63ed36ce0bbe0bc5c2f3bd70977e509e81cafd2e56b6da44dbR17

## Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* Browser version, if have:

## Additional context
I tried lint the whole project, and the result was a lot of changes:

image

When commit these changes, eslint prompts many errors:

image

Some of them need to modify the previously non-standard code, and some need to adjust the rules of eslint to adapt to the project.

Any good suggestions？

### PR DESCRIPTION
**Pull request by Baoyuantop**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [ ] New feature provided
- [x] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**
Run lint-staged on whole project and resolve eslint error.

**Related issues**

resolve #2035 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by iamayushdas** [comment]
Do you think its necessary to do it like this? @Baoyuantop

**Comment by Baoyuantop** [comment]
> Do you think its necessary to do it like this? @Baoyuantop

see #2035  Every time I submit a PR, there will be additional changes

**Review by juzhiyuan — APPROVED** [review]
All changes are made by `yarn prettier xxx`?

**Comment by Baoyuantop** [comment]
> All changes are made by `yarn prettier xxx`?
After run prettier, I  add eslint-disable for 3 test file.

Then merge conflicts with the master branch.

Finally, the e2e test failed, I am going to do it again based on the latest master branch to avoid merge conflicts. Use this to fix failed e2e tests.
Please review later.
@juzhiyuan

**Comment by Baoyuantop** [comment]
move to #2039

**Pull request closed without merging**
