### PR TITLE
feat: support search route by label 

### LINKED ISSUE #861: feat: Route group feature
# why
In order to allow users to filter out routes with a specified group from a large number of routes, I propose to add the route groups feature.

# how
## front-end
In order to finish this feature. There are 3 steps need to do.
- Adding group options to the edit or create route page.
image

- Route group list page
image

- Create or Edit route group page
image

## back-end
Create or update API to match front-end requirements.
- Create route and update route API need to update.
- Route Group List API.
- Create and update route group API.

# APISIX
Need to discuss how to implement route group requirements.

Free to comment here.

cc @juzhiyuan @liuxiran @gxthrj @nic-chen @membphis

### PR DESCRIPTION
**Pull request by starsz**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance

- Related issues
fix #861 
___

### New feature or improvement
- Describe the details and related test reports.

1. Add API for the searching labels.
2. Support filter route by labels.

### CODE REVIEW

**Comment by membphis** [comment]
@starsz this is a big PR, can we split this PR to multiple small PRs?

small PR is easy to review and merge.

**Comment by starsz** [comment]
> @starsz this is a big PR, can we split this PR to multiple small PRs?
> 
> small PR is easy to review and merge, and we can implement this feature step by step

Sure, let me split it.

**Comment by starsz** [comment]
I will split it into two PRs.
The first is #1061.
And after merging, I will push the second PR.

**Comment by nic-chen** [comment]
this PR should be closed now. feel free to reopen it if you need.

**Pull request closed without merging**
