### PR TITLE
fix: inconsistent displayname of updatetime under EN locale

### PR DESCRIPTION
**Pull request by ericsyh**
Signed-off-by: Eric Shen <ericshenyuhao@outlook.com>

Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

There is an in inconsistent display name on the Route, Upstream and SSL pages:
* Route page
route

* Upstream page
上游

* SSL page
SSL

* Consumer page
消费者

So i modified `component.global.updateTime` and `page.upstream.list.edit.time` to keep the display name align as **Update Time**.

**Related issues**

No related issue.

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]
LGTM! After thought for a while, Update Time would be better than Updated At

**Comment by ericsyh** [comment]
@juzhiyuan Any command to trigger the test again? The backend e2e CI failed ....

**Comment by juzhiyuan** [comment]
@ericsyh luarocks.org is unstable today, please be patient. We will help you to trigger it once it's back.

**Comment by ericsyh** [comment]
> @ericsyh luarocks.org is unstable today, please be patient. We will help you to trigger it once it's back.

I see.

**Review by nic-chen — APPROVED** [review]

**Comment by nic-chen** [comment]
@ericsyh  please sync code from branch master to pass backend e2e test.

**Review by starsz — APPROVED** [review]

**Comment by starsz** [comment]
@ericsyh Thanks for your contribution!

**Pull request merged**
