### PR TITLE
feat: support Issue Translator

### PR DESCRIPTION
**Pull request by juzhiyuan**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

support Issue translator for non-english content

**Related issues**

None

**Checklist:**

- [x] Did you explain what problem does this PR solves? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Review by starsz — APPROVED** [review]
Emmm.This feature looks interesting.

**Comment by juzhiyuan** [comment]
How to verify it works 😂

**Comment by juzhiyuan** [comment]
let me ask Infra for a check

**Comment by juzhiyuan** [comment]
wait for Infra: https://issues.apache.org/jira/browse/INFRA-21676

**Comment by juzhiyuan** [comment]
https://cwiki.apache.org/confluence/display/BUILDS/GitHub+Actions+status#GitHubActionsstatus-Security

**Pull request closed without merging**
