### PR TITLE
test: increase timeout value to reduce timeouts

### PR DESCRIPTION
**Pull request by okaybase**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [ ] New feature provided
- [x] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

**Related issues**

fix/resolve:

Improve timeout value to reduce timeouts(like below), update timeout from 500 to 5000.

image
image

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by Baoyuantop** [comment]
Where does the error in the screenshot come from? @okaybase

**Comment by okaybase** [comment]
> Where does the error in the screenshot come from? @okaybase

Hi, from Frontend e2e test.

**Comment by Baoyuantop** [comment]
> > Where does the error in the screenshot come from? @okaybase
> 
> Hi, from Frontend e2e test.

It looks the same as the problem I fixed yesterday #2055 

This error is caused by abnormal rendering of the DOM due to insufficient Github Action performance.

**Comment by okaybase** [comment]
> > > Where does the error in the screenshot come from? @okaybase
> > 
> > 
> > Hi, from Frontend e2e test.
> 
> It looks the same as the problem I fixed yesterday #2055
> 
> This error is caused by abnormal rendering of the DOM due to insufficient Github Action performance.

Github Action performance will affects many test cases, 
but the timeout often happens in this test case(route/search-route.spec.js), so it may be caused by the timeout value 500.

**Comment by liuxiran** [comment]
Hi @okaybase ,thanks for your solution, increasing the waiting time may be a way to fix this ci problem, but the length of waiting time may depend on the network, so would you like to try to add assertion to check the dom status or other ways to solve this problem when it happened again? Not urgent, it seems that this test case can work now.

**Comment by okaybase** [comment]
> Hi @okaybase ,thanks for your solution, increasing the waiting time may be a way to fix this ci problem, but the length of waiting time may depend on the network, so would you like to try to add assertion to check the dom status or other ways to solve this problem when it happened again? Not urgent, it seems that this test case can work now.

okay~ thanks~

**Comment by bzp2010** [comment]
Hi, @okaybase. Are there any solution changes here?

**Review by bzp2010 — APPROVED** [review]

**Review by iamayushdas — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Review by liuxiran — APPROVED** [review]

**Pull request merged**
