### PR TITLE
fix(plugin): set disable but useless

### LINKED ISSUE #1027: bug: when create route with plugin, the disable key should hide in code mirror
# Bug report

## Describe the bug

`disable` key should hide in the code mirror

three reason:
1. user modify `disable` key in code mirror is useless
2. create **route** with the `jwt` or `basic-auth` plugins, when `enable`-> `disable`->`enable`,there will be an error
image
that because `disable` was add to the json,when I delete the disable key and submit, there will be no the error

### LINKED ISSUE #1028: bug: create consumer or route and enable any plugin, will be an error
# Bug report

## Describe the bug

create consumer or route and enable any plugin via **enable button not setting button**, will be an error
except prometheus plugin.

## How to Reproduce
image

### PR DESCRIPTION
**Pull request by juzhiyuan**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance

- Related issues
fix #1027 
fix #1028 

- [x] Use the correct Proxy host;
- [x] Inject the disable property into every plugin's jsonschema, the same as manager-api.

### CODE REVIEW

**Comment by LiteSun** [comment]
CI failed @juzhiyuan

**Comment by juzhiyuan** [comment]
> CI failed @juzhiyuan

cc @nic-chen

**Comment by juzhiyuan** [comment]
There has something I need to confirm with the backend, just wait.

**Review by nic-chen — APPROVED** [review]
the `inject the disable property` part LGTM

**Review by membphis — APPROVED** [review]

**Pull request merged**
