### PR TITLE
fix: fix the upstream timeout unit

### LINKED ISSUE #1565: The upstream timeout unit is seconds instead of milliseconds
image

### PR DESCRIPTION
**Pull request by stu01509**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
Fix #1565

___
### Bugfix
- Description

- How to fix?
Change the upstream timeout unit to s.
image

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]
LGTM, and would like to update those 3 fields' value to `6`? for they are in seconds 🤔 

https://github.com/stu01509/apisix-dashboard/blob/fix-%231565-use-seconds/web/src/components/Upstream/constant.ts#L22-L24

**Comment by stu01509** [comment]
> LGTM, and would like to update those 3 fields' value to `6`? for they are in seconds 🤔
> 
> https://github.com/stu01509/apisix-dashboard/blob/fix-%231565-use-seconds/web/src/components/Upstream/constant.ts#L22-L24

Agree, So I update the commit.

**Comment by liuxiran** [comment]
Hi @stu01509 
For the error in `route/import_export_route.spec.js`, you would try to update these codes to `6`
* https://github.com/apache/apisix-dashboard/blob/9cb4b430e4337a9a1b6a4b3eea4763a76c2feeb7/web/cypress/fixtures/export-route-dataset.json#L43~L45
* https://github.com/apache/apisix-dashboard/blob/9cb4b430e4337a9a1b6a4b3eea4763a76c2feeb7/web/cypress/fixtures/export-route-dataset.json#L96~L98
* https://github.com/apache/apisix-dashboard/blob/9cb4b430e4337a9a1b6a4b3eea4763a76c2feeb7/web/cypress/fixtures/export-route-dataset.json#L148~L150

and for the error https://github.com/apache/apisix-dashboard/pull/1580/checks?check_run_id=2100719617, may need @nic-chen 's help, for this error also occued in https://github.com/apache/apisix-dashboard/pull/1576/checks?check_run_id=2101373014 thanks a lot.

**Comment by nic-chen** [comment]
> Hi @stu01509 
> 
> For the error in `route/import_export_route.spec.js`, you would try to update these codes to `6`
> 
> * https://github.com/apache/apisix-dashboard/blob/9cb4b430e4337a9a1b6a4b3eea4763a76c2feeb7/web/cypress/fixtures/export-route-dataset.json#L43~L45
> 
> * https://github.com/apache/apisix-dashboard/blob/9cb4b430e4337a9a1b6a4b3eea4763a76c2feeb7/web/cypress/fixtures/export-route-dataset.json#L96~L98
> 
> * https://github.com/apache/apisix-dashboard/blob/9cb4b430e4337a9a1b6a4b3eea4763a76c2feeb7/web/cypress/fixtures/export-route-dataset.json#L148~L150
> 
> 
> 
> and for the error https://github.com/apache/apisix-dashboard/pull/1580/checks?check_run_id=2100719617, may need @nic-chen 's help, for this error also occued in https://github.com/apache/apisix-dashboard/pull/1576/checks?check_run_id=2101373014 thanks a lot.
> 
> 

I found the reason, will fix it soon

**Comment by stu01509** [comment]
Hi @liuxiran and @nic-chen 

Thanks for point out, so should I fix the E2E test error or waiting for @nic-chen  to solve it?

**Comment by liuxiran** [comment]
> Hi @liuxiran and @nic-chen
> 
> Thanks for point out, so should I fix the E2E test error or waiting for @nic-chen to solve it?

you can  try to fix the e2e error in `route/import_export_route.spec.js` first😊 @stu01509

**Comment by nic-chen** [comment]
thanks @liuxiran

**Comment by stu01509** [comment]
Hi @liuxiran  and @nic-chen 

Update the commit, fix the **import_export_route.spec.js** compare file error.

**Comment by nic-chen** [comment]
wait for #1594

**Comment by nic-chen** [comment]
hi, please sync codes from branch master.

**Comment by stu01509** [comment]
> hi, please sync codes from branch master.

Done!

**Review by LiteSun — APPROVED** [review]

**Pull request merged**
