### PR TITLE
feat: improved plugin #1631

### LINKED ISSUE #1631: improve Plugin & Plugin Editor & Meta Raw Data Editor module
Here are some minor issues on the Plugin & Plugin Editor & Meta Raw Data Editor page we could resolve.

## Plugin TODO

- [ ] Search area, using Table's own, using fuzzy search.
- [ ] page title not internationalized: configure global plugins/Configure Global Plugin.
- [ ] Add icon for Plugin Marketplace plugins.
- [ ] list page top title, add description: list of enabled plugins.
- [ ] list page, edit button in action area modified to: `配置/Configure`.

## Plugin Editor

- [ ] Some Auth plugins do not need to be configured, in the Data Editor, to disable the input of content.
- [ ] The button is not internationalized.
- [ ] Document button fits too close to JSON button.
- [ ] JSONSchema checks for error messages, which can be divided into: error message + view details.
- [ ] CodeMirror code error highlighting.

## Meta Raw data editor (Route List page)
- [ ] Button not internationalized.
- [ ] layout needs to be adjusted, with additional scrolling axes.

### PR DESCRIPTION
**Pull request by iamayushdas**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

 * [x]  list page top title, add description: list of enabled plugins.
 * [x]  list page, edit button in action area modified to: `配置/Configure`.

screencapture-192-168-43-234-8000-plugin-list-2021-03-24-22_13_55
screencapture-192-168-43-234-8000-plugin-list-2021-03-24-22_13_39

**Related issues**

fix/resolve #1631 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by iamayushdas** [comment]
@juzhiyuan @liuxiran @nic-chen @imjoey 
Please review this PR #1666

**Comment by iamayushdas** [comment]
image

Is this an issue from my side or something else?

**Comment by juzhiyuan** [comment]
no, maybe Cypress's CDN is unstable? let's retrigger

**Comment by iamayushdas** [comment]
@juzhiyuan @LiteSun @bzp2010 @guoqqqi please review this

**Comment by guoqqqi** [comment]
Hi, @iamayushdas  I think the headings should be left-justified.
image

**Review by juzhiyuan — APPROVED** [review]

**Comment by iamayushdas** [comment]
> Hi, @iamayushdas I think the headings should be left-justified.
> image

can you suggest me the exact fix in changes required?

**Comment by juzhiyuan** [comment]
image

How about here?

**Comment by iamayushdas** [comment]
> image
> 
> 
> 
> How about here?

Yes sure will put that there☺️

**Comment by iamayushdas** [comment]
> image
> 
> How about here?

#1671 @juzhiyuan

**Pull request closed without merging**
