### PR TITLE
docs: modify some txt tips to correct grammar

### PR DESCRIPTION
**Pull request by okaybase**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**
Modify some txt tips to correct grammar.

- [ ] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [x] Improve document
- [ ] Backport patches

**What changes will this PR take into?**

Please update this section with detailed description.

**Related issues**

fix/resolve #Modify some txt tips to correct grammar.

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [x] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Review by iamayushdas — APPROVED** [review]
Nice catch @okaybase 👍🏻

**Review by juzhiyuan — APPROVED** [review]

**Comment by okaybase** [comment]
Thanks for your review. @iamayushdas @juzhiyuan

**Comment by iamayushdas** [comment]
you can cc @liuxiran @LiteSun

**Comment by okaybase** [comment]
Okay, thanks for your tip! @iamayushdas :smile:

**Review by LiteSun — APPROVED** [review]

**Review by gxthrj — APPROVED** [review]

**Pull request merged**
