### PR TITLE
feat(cli): Show GitHash for manager-api in branch v2.3 (backport #1162)

### PR DESCRIPTION
**Pull request by imjoey**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance

- Related issues

#1155 .

___
### New feature or improvement
- Describe the details and related test reports.

As discussed with @juzhiyuan https://github.com/apache/apisix-dashboard/pull/1162#issuecomment-752901239 , in order to prepare for the release of `v2.3`, this PR is going to cherry-pick #1162 back to `v2.3` branch. It's also noted that we set `2.3` to `api/VERSION` here, instead of `master` in #1162 .

### CODE REVIEW

**Comment by imjoey** [comment]
ping @juzhiyuan @nic-chen , reviews and comments are welcome. Thanks.

**Review by liuxiran — APPROVED** [review]
LGTM
Btw, will the branch v2.3 be merged into master once the M2.3 is ready?  If so, we have to skip this pr when merging.

**Comment by imjoey** [comment]
> LGTM
> Btw, will the branch v2.3 be merged into master once the M2.3 is ready? If so, we have to skip this pr when merging.

@liuxiran thanks. I believe it's rather important. Definitely this PR will introduce a slight conflict between M2.3 and master branch: `./api/VERSION`. IMHO, we can still continue to merge, with resolving the conflicts. 😄 

What's your insights? @juzhiyuan

**Comment by juzhiyuan** [comment]
> LGTM
> Btw, will the branch v2.3 be merged into master once the M2.3 is ready? If so, we have to skip this pr when merging.

The branch v2.3 will be merged once we completed the release process (pushing the package to Apache SVN and complete the VOTE).

**Pull request merged**
