### PR TITLE
chore: Show the correct lines of code in manager logger

### PR DESCRIPTION
**Pull request by gxthrj**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance

### CODE REVIEW

**Comment by membphis** [comment]
@nic-chen @ShiningRush please take a look at this PR

**Comment by nic-chen** [comment]
I think we should add a cli test case for it to make sure the change works fine.

**Comment by gxthrj** [comment]
ok, try to add some logger test .

**Review by spacewander — APPROVED** [review]

**Comment by juzhiyuan** [comment]
ping @gxthrj

**Review by membphis — APPROVED** [review]

**Comment by membphis** [comment]
@gxthrj please fix the conflict first

**Comment by juzhiyuan** [comment]
ping @gxthrj

**Comment by membphis** [comment]
@gxthrj you need to resolve the conflict

**Comment by gxthrj** [comment]
Close this issue， the caller skip has been added in other PR.

**Pull request closed without merging**
