### PR TITLE
fix: delete POST method in /apisix/admin/consumer 

### LINKED ISSUE #852: bug: manager-api supported `POST` method for consumer
# Bug report

## Describe the bug
manager-api supported `POST` method for consumer.
but it should not support the `POST` method for consumer, the same as APISIX's adminapi.
```testcase
{
			caseDesc: "create consumers with post method",
			Object:   MangerApiExpect(t),
			Path:     "/apisix/admin/consumers",
			Method:   http.MethodPost,
			Body: `{
				"username":"case_9",
				"desc": "new consumer",
				"create_time": 1602883670,
				"update_time": 1602893670
		   }`,
			Headers:      map[string]string{"Authorization": token},
			ExpectStatus: http.StatusMethodNotAllowed,
		},
```

### PR DESCRIPTION
**Pull request by starsz**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance

- Related issues

fix #852
related #868

### CODE REVIEW

**Comment by starsz** [comment]
Ping @juzhiyuan. Help me look at the frontend CI.

**Comment by juzhiyuan** [comment]
cc @LiteSun

**Comment by idbeta** [comment]
> cc @idbeta @LiteSun

It seems that the case is unstable. Let me try to fix it. Please help me to rerun the test first.

**Comment by idbeta** [comment]
@LiteSun because this PR remove `post` method, so the frontend should use `put` replace `post` when submitting consumer. 
image
@starsz @membphis @juzhiyuan I think the prompt information is not humane enough, what do you think?

**Comment by LiteSun** [comment]
> @LiteSun the e2e test was right. because this PR remove `post` method, so the frontend should use `put` replace `post` when submitting consumer. otherwise, create consumer would failed.
> image
> @starsz error code should not be `undefined`
> @starsz @membphis @juzhiyuan I think the prompt information is not humane enough, what do you think?

change `POST` to  `PUT` when creating consumer, let's wait for CI .

**Comment by tokers** [comment]
@starsz Please solve the conflicts firstly.

**Review by tokers — APPROVED** [review]

**Review by tokers — CHANGES_REQUESTED** [review]
Conflict.

**Comment by starsz** [comment]
> @starsz error code should not be undefined

Yes, I think we need to fix the error code for all API that the method is not allowed.
That should be done in another PR.

**Review by tokers — APPROVED** [review]

**Review by nic-chen — APPROVED** [review]

**Pull request merged**
