### PR TITLE
fix: caller location error in logs

### LINKED ISSUE #2365: bug: caller in log is positioning error
### Issue description

caller in log is positioning error

### Expected behavior

caller should is internal/filter/logging.go:45

https://github.com/apache/apisix-dashboard/blob/561ed377ec2237707bb8c78623e336360c6c6463/api/internal/filter/logging.go#L44-L57

### How to Reproduce

1. start apisix-dashboard
2. send request
3. view access.log

### Screenshots

_No response_

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have: 
- Browser version, if have:

### Additional context

I want to solve it

### PR DESCRIPTION
**Pull request by jwrookie**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Please update this section with detailed description.

**Related issues**

fix/resolve #2365

**Checklist:**

- [ ] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Review by starsz — COMMENTED** [review]
Can you add a test case to cover it?
Refer: https://github.com/apache/apisix-dashboard/blob/master/api/test/shell/cli_test.sh

**Comment by jwrookie** [comment]
> Can you add a test case to cover it? Refer: https://github.com/apache/apisix-dashboard/blob/master/api/test/shell/cli_test.sh

ok

**Comment by jwrookie** [comment]
> Can you add a test case to cover it? Refer: https://github.com/apache/apisix-dashboard/blob/master/api/test/shell/cli_test.sh

done!

**Comment by jwrookie** [comment]
have a check ,thx @starsz @nic-chen

**Review by starsz — APPROVED** [review]

**Review by nic-chen — APPROVED** [review]

**Comment by jwrookie** [comment]
have a check, thx @bzp2010

**Review by bzp2010 — APPROVED** [review]

**Pull request merged**
