### PR TITLE
feat: rewrite route-with-jwt-plugin-test using ginkgo

### PR DESCRIPTION
**Pull request by bisakhmondal**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Please update this section with detailed description.

**Related issues**
#1500 

**Checklist:**

- [ ] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by juzhiyuan** [comment]
@nic-chen same pending here

**Comment by nic-chen** [comment]
@bisakhmondal  
please push a new commit to trigger ci, if fail again, I think we may need to create a new PR

**Comment by bisakhmondal** [comment]
Okay

**Comment by juzhiyuan** [comment]
@bisakhmondal Hi, please sync codes to your branch, the FE CI will get fixed.

**Comment by nic-chen** [comment]
hi @bisakhmondal 
I think you could try to create a new PR to resolve `Expected`

**Comment by bisakhmondal** [comment]
Okay

**Pull request closed without merging**
