### PR TITLE
Add search functionality for ID, host, and description fields

### LINKED ISSUE #2729: Searching routes by hosts - FR
I would like to see "searching routes by host" section on apisix dashboard

In Routes section there is only searching labels Name Path and Labels. We are mostly need searching with hostname. 
Thats why i want to search it with hosts.

I will glad to help for the implementation.

### PR DESCRIPTION
**Pull request by anldrms**
**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

This PR adds search functionality for fields like ID, host, and description. Users can now search for specific entries in the dataset using keywords in these fields.

**Related issues**

fix/resolve #2729

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by SkyeYoung** [comment]
Please fix this? 
image

**Comment by anldrms** [comment]
> Please fix this? image

Do you know what causes exactly happened?

**Review by Baoyuantop — COMMENTED** [review]
Thank you for your contribution. Codes LGTM! 
You will also need to provide E2E testing for this code, so feel free to ask questions if you have any.

**Comment by anldrms** [comment]
@Baoyuantop could you review it again? I implement the e2e testings.

**Review by SkyeYoung — APPROVED** [review]
LGTM 🤔

**Review by Baoyuantop — APPROVED** [review]

**Review by bzp2010 — APPROVED** [review]

**Comment by bzp2010** [comment]
Nice job, thanks for your contribution!

**Pull request merged**
