### PR TITLE
test: migrate route remote addr e2e

### PR DESCRIPTION
**Pull request by zaunist**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [ ] New feature provided
- [x] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Migrate old route e2e to ginkgo implement.
include:
```
e2e/route_remote_addr_test.go
```

Please update this section with detailed description.

**Related issues**

Part of #2197 

fix/resolve #0001

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by zaunist** [comment]
Hi, @bzp2010 It looks like the stream E2E occur error frequently. Any solution ?

**Comment by zaunist** [comment]
cc @bzp2010 @starsz @nic-chen

**Review by nic-chen — APPROVED** [review]

**Review by starsz — APPROVED** [review]

**Comment by zaunist** [comment]
cc @bzp2010

**Comment by zaunist** [comment]
cc @okaybase @juzhiyuan

**Review by bzp2010 — APPROVED** [review]

**Pull request merged**
