### PR TITLE
feat: Improve consumer for i18n (#1212)(backport to v2.3)

### PR DESCRIPTION
**Pull request by imjoey**
Signed-off-by: imjoey <majunjiev@gmail.com>

Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [x] Backport patches

- Related issues

As the preparation for release v2.3, this PR is going to cherry-pick 50bcbe9 from master branch to v2.3 branch. Regarding to the details, please refer to #1212  .

### CODE REVIEW

**Comment by imjoey** [comment]
@juzhiyuan @liuxiran this PR needs to be marked as `backport`. Thanks.

**Comment by imjoey** [comment]
@juzhiyuan CI seems not triggered ? Commits backported also strongly needs CI verification. 😄

**Comment by juzhiyuan** [comment]
@imjoey yes, that's because the actions only listen on the master branch 🤔

**Comment by imjoey** [comment]
> @imjoey yes, that's because the actions only listen on the master branch 🤔

@juzhiyuan oh, this would lead us in danger. if we consider vX.Y as a stable release, IMHO vX.Y also needs CI, in case introducing additional bugs via bug hot fixes

**Comment by juzhiyuan** [comment]
Could you please file a PR and listen on 2.x?

**Comment by imjoey** [comment]
> Could you please file a PR and listen on 2.x?

@juzhiyuan sure, I will try. Thanks.

**Comment by juzhiyuan** [comment]
Great you are!

**Review by juzhiyuan — APPROVED** [review]
I see this PR is picked from the master, LGTM

**Pull request merged**
