### PR TITLE
feat: add more detailed log messages to authentication.go

### LINKED ISSUE #1964: Feature: add more details log messages in authentication.go
# Feature request

## Please describe your feature

Hi, I found that the log in authentication.go is a little bit less
Like : 

https://github.com/apache/apisix-dashboard/blob/3cfc32761122ad7f15f67edcfc251d0bed2e7538/api/internal/filter/authentication.go#L67-L70

## Describe the solution you'd like

Maybe we can add more details info in it.

Like:

1. How to solve this problem.
```
please check the secret in conf.yaml"
```

### PR DESCRIPTION
**Pull request by burntcarrot**
Add more detailed log messages to authentication.go with new log messages.

Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

This PR will add more detailed log messages to authentication.go with new log messages.

**Related issues**

Fixes #1964 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Review by starsz — APPROVED** [review]

**Comment by burntcarrot** [comment]
I hope we can add this feature soon by merging it, but in order to get this merged, this needs more reviews.

Could you please request reviews from other maintainers too?

**Comment by juzhiyuan** [comment]
@burntcarrot Hi, I will request more reviewers. BTW, would you please check the Backend E2E tests? I'm not sure why it failed.

**Comment by RedemptionC** [comment]
> @burntcarrot Hi, I will request more reviewers. BTW, would you please check the Backend E2E tests? I'm not sure why it failed.

Hi,it failed in [my PR](https://github.com/apache/apisix-dashboard/pull/1968/checks?check_run_id=3058573934) too
I currently don't know why it failed

**Comment by burntcarrot** [comment]
> @burntcarrot Hi, I will request more reviewers. BTW, would you please check the Backend E2E tests? I'm not sure why it failed.

@juzhiyuan I can confirm that these tests aren't failing due to the changes made in this PR. These are getting failed in other PRs too as mentioned by @RedemptionC.

Those tests are failing due to some misconfiguration for some endpoints, I can see some requests returning `404` and `400` status codes in the traceback, here's an example:

```
• Failure [0.053 seconds]
Upstream update use patch method [It] create upstream via POST 
/home/runner/work/apisix-dashboard/apisix-dashboard/api/test/e2enew/upstream/upstream_test.go:721

  
  	Error Trace:	reporter.go:23
  	            				chain.go:21
  	            				response.go:585
  	            				response.go:151
  	            				base.go:191
  	            				upstream_test.go:734
  	            				runner.go:113
  	            				runner.go:64
  	            				it_node.go:26
  	            				spec.go:215
  	            				spec.go:138
  	            				spec_runner.go:200
  	            				spec_runner.go:170
  	            				spec_runner.go:66
  	            				suite.go:79
  	            				ginkgo_dsl.go:229
  	            				ginkgo_dsl.go:210
  	            				upstream_suite_test.go:31
  	Error:      	
  	            	expected status equal to:
  	            	 "200 OK"
  	            	
  	            	but got:
  	            	 "400 Bad Request"
  	Test:       	Upstream update use patch method create upstream via POST
  

  /home/runner/go/pkg/mod/github.com/gavv/httpexpect/v2@v2.1.0/reporter.go:23
```

**Review by nic-chen — APPROVED** [review]

**Comment by juzhiyuan** [comment]
> > @burntcarrot Hi, I will request more reviewers. BTW, would you please check the Backend E2E tests? I'm not sure why it failed.
> 
> Hi,it failed in [my PR](https://github.com/apache/apisix-dashboard/pull/1968/checks?check_run_id=3058573934) too
> I currently don't know why it failed

cc @nic-chen to have a look.

**Review by Jaycean — APPROVED** [review]

**Pull request merged**
