### PR TITLE
fix: route search test optimised

### LINKED ISSUE #1925: fe test: optimize cy.load() in  search route test case
got it @iamayushdas , we can optimize this point in a new pr

_Originally posted by @liuxiran in https://github.com/apache/apisix-dashboard/pull/1918#discussion_r642588962_

### PR DESCRIPTION
**Pull request by iamayushdas**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [ ] New feature provided
- [x] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

cy.reload() were optimised so that test can be more efficient and fast.
test running time decreased by 27+ seconds @liuxiran 

**Related issues**

fix/resolve #1925 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by iamayushdas** [comment]
cc @LiteSun @liuxiran @nic-chen

**Comment by iamayushdas** [comment]
@juzhiyuan can i have the review on it and also can you give reply on slack :pleading_face:

**Review by liuxiran — APPROVED** [review]
> **Checklist:**
> 
> * [z] Did you explain what problem does this PR solve? Or what new features have been added?

Nice work~! Thanks @iamayushdas , BTW could you please update the issue checklist item 1 `[z]` to `[x]`?

**Comment by iamayushdas** [comment]
> > **Checklist:**
> 
> > 
> 
> > * [z] Did you explain what problem does this PR solve? Or what new features have been added?
> 
> 
> 
> Nice work~! Thanks @iamayushdas , BTW could you please update the issue checklist item 1 `[z]` to `[x]`?

Haha, yes yes, also could you tell some way to contact you? Like when i need some help in FE?

**Comment by liuxiran** [comment]
> > > **Checklist:**
> > 
> > 
> > > 
> > 
> > 
> > > * [z] Did you explain what problem does this PR solve? Or what new features have been added?
> > 
> > 
> Haha, yes yes, also could you tell some way to contact you? Like when i need some help in FE?

Slack would be a better way ^-^, I wonder if you have alreay in some spaces which other members in, if so you can send me an  invitation

**Comment by iamayushdas** [comment]
Whats your userid on slack #apisix channel?

**Comment by liuxiran** [comment]
> Whats your userid on slack #apisix channel?￼ @liuxiran

Xiran Liu

**Review by juzhiyuan — APPROVED** [review]

**Review by LiteSun — APPROVED** [review]

**Pull request merged**
