### PR TITLE
docs: update FAQ in user guide

### PR DESCRIPTION
**Pull request by KishaniKandasamy**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [X] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**
update FAQ

Please update this section with detailed description.

**Related issues**

fix: #1804 

**Checklist:**

- [X] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]

**Review by liuxiran — APPROVED** [review]
LGTM

could we ignore the ci problem? 
cc @juzhiyuan @nic-chen

**Review by nic-chen — APPROVED** [review]

**Comment by juzhiyuan** [comment]
Yep

**Review by Jaycean — APPROVED** [review]
LGTM

**Comment by Jaycean** [comment]
@KishaniKandasamy 
Please change the title format, add a semantic PR title.
docs : update FAQ in user guide -> docs: update FAQ in user guide

**Comment by imjoey** [comment]
@KishaniKandasamy Hi, please rebase the code to resolve conflicts. Thanks.

**Comment by KishaniKandasamy** [comment]
> @KishaniKandasamy Hi, please rebase the code to resolve conflicts. Thanks.

done

**Review by starsz — APPROVED** [review]

**Pull request merged**
