### PR TITLE
docs: update architecture diagram.

### PR DESCRIPTION
**Pull request by membphis**
update architecture diagram

### CODE REVIEW

**Comment by membphis** [comment]
image

**Comment by juzhiyuan** [comment]
cc @nic-chen @starsz  to check the Backend E2E.

**Comment by starsz** [comment]
> cc @nic-chen @starsz to check the Backend E2E.

Maybe there was some change on apisix. It needs time to check.

**Comment by nic-chen** [comment]
E2E test failed because of an update of global rule in APISIX a few days ago.. I submitted a pr to fix this problem.

https://github.com/apache/apisix/pull/3595

**Comment by juzhiyuan** [comment]
Hi, please sync your codes with the master branch to fix the CI failure.

**Review by starsz — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
