### PR TITLE
test: Remove wait Reduce test time

### LINKED ISSUE #1371: reduce plugin testcases' running time
# Feature request

## Please describe your feature

image

Plugin Test takes a long time to run.

### PR DESCRIPTION
**Pull request by guoqqqi**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [ ] New feature provided
- [x] Improve performance
- [ ] Backport patches

- Related issues
resolve #1371 
___
Reduce the test time of `schema-smocktest` by removing the `wait` from the global functions

### CODE REVIEW

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-dashboard/issues/1470

**Comment by juzhiyuan** [comment]
Hi, please sync your codes with the master branch to fix the CI failure.

**Comment by liuxiran** [comment]
2021-02-18 13-06-59屏幕截图

I tried this pr branch locally, and found that sometimes the delete test case ran failed, which happened due to four plugins involved in case were not successfully enabled, so there is not any plugins in the plugin list.
It is likely to increase the instability of this test case, If you can reproduce this error locally(maybe you need to try more  times), we'd better tried other way to reduce test time in this test case ^_^ @guoqqqi

**Comment by guoqqqi** [comment]
OK, let me check

**Comment by guoqqqi** [comment]
Hi, I saw that the two tests in the plugin had something in common, so I combined the two tests into one test and successfully removed the `wait()`

**Review by membphis — COMMENTED** [review]
LGTM

**Comment by juzhiyuan** [comment]
Hi @qier222 , you could have a try to review this PR :)

**Review by liuxiran — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
