### PR TITLE
fix: Incomplete i18n coverage

### PR DESCRIPTION
**Pull request by Baoyuantop**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
#1514 
___
### Bugfix
- Description
fixed Incomplete i18n coverage
- How to fix?
Upgraded `@ant-design/pro-table` component to the latest version
___
### New feature or improvement
- Describe the details and related test reports.

___
### Please add the corresponding test cases if necessary.

___
### Backport patches
- Why need to backport?

- Source branch

- Related commits and pull requests

- Target branch

### CODE REVIEW

**Comment by juzhiyuan** [comment]
cc @guoqqqi to review.

**Review by guoqqqi — APPROVED** [review]

**Review by guoqqqi — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Comment by juzhiyuan** [comment]
CI failed

**Comment by LiteSun** [comment]
@nic-chen  Backend CLI Test failed，please take a look when you have time

**Comment by nic-chen** [comment]
Strange, there is no problem with other PRs.
Could you sync the master code first please? @Baoyuantop

**Comment by nic-chen** [comment]
After I synchronized the master code, it did not appear again. I feel that it was affected by the github CI mechanism. The backend cli test has not been updated for a while.

**Comment by liuxiran** [comment]
https://github.com/apache/apisix-dashboard/pull/1538/checks?check_run_id=2084118899

try to fix in #1590

**Review by LiteSun — APPROVED** [review]

**Review by bzp2010 — APPROVED** [review]

**Review by nic-chen — APPROVED** [review]

**Review by liuxiran — APPROVED** [review]

**Comment by liuxiran** [comment]
merged, thanks a lot

**Pull request merged**
