### PR TITLE
fix: Add version ldflags for building manager-api in Dockerfile

### LINKED ISSUE #1350: bug: starting the Manager API in docker does not display the version number
# Bug report

## Describe the bug

When starting the Manager API should display some info like:
```
Version : 2.3
GitHash : c1e08be6
Listen  : 127.0.0.1:9000
Loglevel: warn
Logfile : /usr/local/apisix-dashboard/api/logs/error.log
```

but starting the Manager API in docker does not display the version number

## System information

- OS: [e.g. macOS, Windows]  docker
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [e.g. 2.0-rc3] 2.3

### PR DESCRIPTION
**Pull request by imjoey**
Signed-off-by: imjoey <majunjie@apache.org>

Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues

Fixes #1350 .

___
### Bugfix
- Description

At previous manager-api build phase in Dockerfile, the ldflags of `github.com/apisix/manager-api/cmd.Version` and `github.com/apisix/manager-api/cmd.GitHash` are missing. This lead to the no `Version` output when running `manager-api`, as described in #1350 .

- How to fix?

Add missing `ldflags` in Dockerfile. For simplicity, this PR is going to reuse the existing built script `./api/build.sh` to compile out the binary. 

In addition, this PR will also reduce the usage of `RUN` commands for smaller image size.

- Additional 

FYI, since there is no `.githash` or `.git/` within the artifact downloaded from Github , the `GitHash` output is still missing.

### CODE REVIEW

**Comment by imjoey** [comment]
ping @nic-chen @starsz  @moonming  for reviewing. Thanks.

**Comment by nic-chen** [comment]
@imjoey thanks 
we could run test for it，please refer https://github.com/apache/apisix-dashboard/blob/master/.github/workflows/deploy-with-docker.yml
but don't push the image

**Comment by imjoey** [comment]
> @imjoey thanks
> we could run test for it，please refer https://github.com/apache/apisix-dashboard/blob/master/.github/workflows/deploy-with-docker.yml
> but don't push the image

@nic-chen thanks for the direction. An additional CI test triggered on pull request is added for docker testing. Any feedback is welcome.

**Comment by nic-chen** [comment]
> > @imjoey thanks
> > we could run test for it，please refer https://github.com/apache/apisix-dashboard/blob/master/.github/workflows/deploy-with-docker.yml
> > but don't push the image
> 
> @nic-chen thanks for the direction. An additional CI test triggered on pull request is added for docker testing. Any feedback is welcome.

well done! thanks.

**Review by nic-chen — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
