### PR TITLE
feat: add a unit test for consumer and remove implicit init

### PR DESCRIPTION
**Pull request by ShiningRush**
- add a real unit test for consumer `Get`
- remove implicit init function, go is not recommended.

### CODE REVIEW

**Comment by nic-chen** [comment]
Good job.Thanks.

We need to enable CI for v2.1 to test.

**Comment by nic-chen** [comment]
@ShiningRush  

please change base to `master`

**Comment by juzhiyuan** [comment]
It seems that there have a lot of changes with the master branch, maybe related to squash?

**Comment by juzhiyuan** [comment]
emmm may need cherry-pick

**Comment by ShiningRush** [comment]
I open a new PR(#859 ) for it.

**Pull request closed without merging**
