### PR TITLE
chore: sync JSON Schema

### PR DESCRIPTION
**Pull request by okaybase**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Please update this section with detailed description.

**Related issues**

fix/resolve: sync JSON Schema

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-dashboard/pull/1999/files

@nic-chen has synced the schema.json with Apache APISIX 2.7

**Comment by nic-chen** [comment]
@okaybase 
thanks, but we couldn't sync it now.

**Comment by juzhiyuan** [comment]
@nic-chen Please leave more detailed reasons, thanks.

**Comment by okaybase** [comment]
> @nic-chen Please leave more detailed reasons, thanks.

@nic-chen @juzhiyuan haha :smile:  it doesn't matter, maybe i can understand.

**Comment by juzhiyuan** [comment]
so could you close this PR? because we are going to be compatible with 2.7 version :)

**Comment by okaybase** [comment]
> so could you close this PR? because we are going to be compatible with 2.7 version :)

of course~

**Pull request closed without merging**
