### PR TITLE
refactor: config

### PR DESCRIPTION
**Pull request by bzp2010**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [x] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Refactor configuration module.

### CODE REVIEW

**Comment by bzp2010** [comment]
### Note that the code in the current branch will not pass compilation and CI is temporarily closed. When we finish all break updating, we will focus on the build and testing issues.

**Review by nic-chen — COMMENTED** [review]
In my opinion, PR should not be merged without CI passed. Either do compatibility first, or remove the code first and add them back part by part.

**Comment by starsz** [comment]
> In my opinion, PR should not be merged without CI passed. Either do compatibility first, or remove the code first and add them back part by part.

Agree +1

**Comment by LiteSun** [comment]
> In my opinion, PR should not be merged without CI passed. Either do compatibility first, or remove the code first and add them back part by part.

+1

**Comment by bzp2010** [comment]
### Update

It currently completes the refactoring of the `config` package without touching any meaningful CI tests, and eliminates all other package coupling dependencies on `conf`, and currently it completely uses parameter passing to pass configuration to dependencies.

However, it should be noted that part of the CI related to release packaging is turned off and it will be turned on when the v3 version on the `next` branch is ready for release. Also the current configuration pass has been modified so that some of the function arguments have been changed, they are crude and only meet the criteria of being usable, not elegant, I need to optimize them further in iterations, please don't get hung up on the function argument changes.

### Tips

The core of this PR is to remove the `conf` package, implement the new `config` package, strip and replace its use cases. I had to modify a lot of coupled code and related test CIs, such as CLI and E2E. So this PR was huge, involving many files and hundreds of lines of code changes. You can focus on those new feature implementations rather than simply replacing code with packages.

**Comment by bzp2010** [comment]
ping @nic-chen @starsz @LiteSun

**Review by starsz — APPROVED** [review]

**Review by nic-chen — APPROVED** [review]

**Pull request merged**
