### PR TITLE
docs: update FAQ.md to include SPA deployment

### PR DESCRIPTION
**Pull request by CGerAJ**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [ ] New feature provided
- [x] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Please update this section with detailed description.

**Related issues**
configure a single-page application(SPA) in APISIX

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [x] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by bzp2010** [comment]
I think that when using the APISIX proxy to access the dashboard, you only need to create a route and use the port of the Manager API as the upstream address.

Currently, static resource requests are completely handled by the built-in HTTP server of the Manager API.

**Comment by CGerAJ** [comment]
How to configure my own SPA？ is not APISIX dashboard

as you known, static SPA index.html not has port.

http://apisix.apache.org/zh/docs/apisix/FAQ/#%E5%A6%82%E4%BD%95%E9%80%9A%E8%BF%87-apisix-%E4%BB%A3%E7%90%86%E8%AE%BF%E9%97%AE-apisix-dashboard

Is there a problem with my understanding?
The content presented in the document does not meet the requirements。


@bzp2010

**Comment by bzp2010** [comment]
> How to configure my own SPA？ is not APISIX dashboard
> 
> as you known, static SPA index.html not has port.
> 
> http://apisix.apache.org/zh/docs/apisix/FAQ/#%E5%A6%82%E4%BD%95%E9%80%9A%E8%BF%87-apisix-%E4%BB%A3%E7%90%86%E8%AE%BF%E9%97%AE-apisix-dashboard
> 
> Is there a problem with my understanding?
> The content presented in the document does not meet the requirements。

Hi, @CGerAJ. I fully understand what you mean.

1. About SPA deploy
For SPA, although APSIX can support it, it is still based on the old nginx mode (edit `nginx.conf` by `config.yaml`), which can not give full play to the dynamic advantages of APISIX.
Personally, I recommend that you use another nginx instance to proxy it; The way of customizing nginx configuration is not elegant and cannot be extended to multiple nodes.

2. About this PR
I recommend that you use a short description attached with a link to link it to the APISIX documentation. Both of by `route with upstream` and `customize Nginx configure`.
BTW, you should change the PR title to normally format

cc @liuxiran @juzhiyuan What do you suggest?

**Comment by juzhiyuan** [comment]
Yes, although Apache APISIX could support Static files, it's not recommended to use like this way 🤔

**Comment by liuxiran** [comment]
As @bzp2010 said, we recommend using  APISIX way to solve the problem so that you can experience the advantages of APISIX

> as you known, static SPA index.html not has port.

sorry, I did not got you this point @CGerAJ .  From your doc, let`s suppose that your SPA was deploied in 127.0.0.1：8099, and you can visit 
`http://127. 0.0.1:8099/` to visit your SPA app. 

you can just publish a route with upstream `127.0.0.1:8099` with uri `/*`, maybe you would wonder how to proxy any uri  to your upstream `/` or `/index.html` right? If so you can refer to `proxy-rewrite` plugin
Please let me know whether I have any misunderstanding, Thank you

**Comment by CGerAJ** [comment]
I get it,Deployment Spa with APSIX is not recommended

**Comment by juzhiyuan** [comment]
cc @tzssangglass

**Comment by tzssangglass** [comment]
> 抄送@tzssangglass

what do I need to do

**Comment by juzhiyuan** [comment]
> I get it, Deployment Spa with APSIX is not recommended

@tzssangglass I'd like to ask you for a confirmation 🙈🙈

**Comment by tzssangglass** [comment]
Yes, APISIX is suitable as an API proxy and is not recommended as a static file proxy.

**Pull request closed without merging**
