### PR TITLE
feat(route): remove key-auth plugin tip

### LINKED ISSUE #2092: Feature request: supporting key-auth plugin to get key from query string
# Feature request

## Please describe your feature

refer to https://github.com/apache/apisix/pull/4490, currently we can configure `key-auth` plugin in Route and Service with `header` or `query` properties, so we should remove the tip in the `key-auth` configure page when create/configure Route 、 Service and global plugin

image

### PR DESCRIPTION
**Pull request by zaunist**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

remove the tip in the key-auth configure page when create/configure route 、 service and global plugin.

**Related issues**

resolve #2092 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by zaunist** [comment]
image

**Comment by LiteSun** [comment]
The CI failed and just helped you re-run the CI.

**Comment by zaunist** [comment]
@juzhiyuan Please help me to re run failed CI, thanks.

**Comment by juzhiyuan** [comment]
done

**Comment by juzhiyuan** [comment]
done

**Comment by juzhiyuan** [comment]
done

**Comment by zaunist** [comment]
cc @LiteSun @okaybase @bzp2010

**Review by guoqqqi — APPROVED** [review]
LGTM

**Review by Baoyuantop — APPROVED** [review]
Need to deal with more special cases

**Review by okaybase — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Review by LiteSun — APPROVED** [review]

**Pull request merged**
