### PR TITLE
feat: support proto API

### PR DESCRIPTION
**Pull request by bzp2010**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Add `proto` entity support to Manager API.

**Related issues**

resolve part of #1378 #1449 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [x] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by bzp2010** [comment]
Do you have any suggestions on compiling and verifying the correctness of `protobuf` syntax in real-time? 
I haven't found a way to integrate this function into the program, most of which is the use of CLI.

**Comment by bzp2010** [comment]
Hi, everyone. This is some information about the current PR.

### Update: 
completed code writing

### Current limitations:
Now I haven't found a way to integrate the protobuf golang generator into the program, so I can't verify the protobuf entered by the user in real time and point out the error.
I noticed that software such as `protoc-gen-go` and `protoc-gen-gogo` are written as `protoc` plugins, completely using `stdin` and `stdout` to interact with `protoc`, and there is no need to consider the possibility of introducing other programs as dependency libraries.

### Need help:
I wonder if you have a better way. If so, please point it out and I will continue to improve it.

**Comment by juzhiyuan** [comment]
Hi @ShiningRush @shuaijinchao, any ideas about this?

**Review by nic-chen — COMMENTED** [review]
the PR is too big. We could split it into several small PRs.

**Comment by bzp2010** [comment]
> the PR is too big. We could split it into several small PRs.

Yes, I think so. I will try it.

BTW, should I split to function, unit test, e2e test, that 3 PRs?

**Comment by nic-chen** [comment]
> > the PR is too big. We could split it into several small PRs.
> 
> Yes, I think so. I will try it.
> 
> BTW, should I split to function, unit test, e2e test, that 3 PRs?


We could split it to: `structure and schema definition`, `create`... 
And each PR has corresponding complete test cases.
That would be better.

**Comment by bzp2010** [comment]
Hi, @nic-chen.
The first part of split PR: data entity has been added. This section does not cover test code.

Link Here: [https://github.com/apache/apisix-dashboard/pull/2144](https://github.com/apache/apisix-dashboard/pull/2144)

**Pull request merged**
