### PR TITLE
feat: add dashboard overview

### PR DESCRIPTION
**Pull request by zaunist**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

added dashboard backend API for apisix status summary.

**Related issues**

ref https://summer.iscas.ac.cn/#/org/prodetail/210050270

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by zaunist** [comment]
This interface return data just similar to:
```
{
    "code": 0,
    "message": "",
    "data": {
        "router_cnt": 1,
        "online_router_cnt": 1,
        "upstream_cnt": 5,
        "dashboard_version": "2.10.1",
        "gateway_info": [
            {
                "id": "1c5195b7-7e06-429e-a476-29d598fb0966",
                "last_report_time": 1640940698,
                "up_time": 119,
                "boot_time": 1640940579,
                "etcd_version": "3.5.0",
                "hostname": "ubuntu",
                "version": "2.11.0"
            }
        ],
        "plugins": [
            "api-breaker",
            "authz-casbin",
            "authz-keycloak",
            "azure-functions",
            "basic-auth",
            "batch-requests",
            "client-control",
            "consumer-restriction",
            "cors",
            "datadog",
            "dubbo-proxy",
            "echo",
            "error-log-logger",
            "example-plugin",
            "ext-plugin-post-req",
            "ext-plugin-pre-req",
            "fault-injection",
            "grpc-transcode",
            "gzip",
            "hmac-auth",
            "http-logger",
            "ip-restriction",
            "jwt-auth",
            "kafka-logger",
            "key-auth",
            "ldap-auth",
            "limit-conn",
            "limit-count",
            "limit-req",
            "log-rotate",
            "node-status",
            "openid-connect",
            "prometheus",
            "proxy-cache",
            "proxy-mirror",
            "proxy-rewrite",
            "real-ip",
            "redirect",
            "referer-restriction",
            "request-id",
            "request-validation",
            "response-rewrite",
            "server-info",
            "serverless-post-function",
            "serverless-pre-function",
            "skywalking",
            "skywalking-logger",
            "sls-logger",
            "syslog",
            "tcp-logger",
            "traffic-split",
            "ua-restriction",
            "udp-logger",
            "uri-blocker",
            "wolf-rbac",
            "zipkin"
        ]
    },
    "request_id": "db0b5cc6-a25b-4599-996b-8576a8941e43"
}
```

**Comment by zaunist** [comment]
cc @starsz @nic-chen

**Comment by bzp2010** [comment]
Hi, @zaunist.

Is this a standard implementation source from APISIX?

**Comment by zaunist** [comment]
we will complete this feature in #2152

**Pull request closed without merging**
