### PR TITLE
feat: added front-end e2e coverage report in ci

### PR DESCRIPTION
**Pull request by LiteSun**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [ ] New feature provided
- [x] Improve performance
- [ ] Backport patches

### CODE REVIEW

**Comment by juzhiyuan** [comment]
Hi, please sync your codes with the master branch to fix the CI failure.

**Comment by liuxiran** [comment]
May I ask where can I find the fe e2e test coverage report? It seems that the `Codecov Report` only contians be, thanks.

**Comment by LiteSun** [comment]
> May I ask where can I find the fe e2e test coverage report? It seems that the `Codecov Report` only contians be, thanks.

The results of the test coverage are printed in the ci terminal.
image

**Comment by juzhiyuan** [comment]
How to submit comment like `codecov-io`?

**Comment by juzhiyuan** [comment]
`yarn.lock` has too many changes, please check if it's necessary.

**Review by juzhiyuan — APPROVED** [review]

**Review by bzp2010 — APPROVED** [review]

**Pull request merged**
