### PR TITLE
ci: run e2e test parallel

### PR DESCRIPTION
**Pull request by qsliu2017**
**Why submit this pull request?**

- [ ] Bugfix
- [ ] New feature provided
- [x] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

currently, frontend e2e tests take a very long time up to 30min. this PR aims to run cypress tests parallelly. In my test(https://github.com/qsliu2017/apisix-dashboard/actions/runs/1161286081), this can decrease the frontend e2e test to 6 min!!

**Related issues**

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by qsliu2017** [comment]
to run cypress parallelly, it requires a [Cypress Dashboard](https://docs.cypress.io/guides/dashboard/introduction) account and set it in this repo's secrets. can we register an official account? @juzhiyuan

**Comment by liuxiran** [comment]
cc @LiteSun please help to take a look when you have time, thanks a lot

**Comment by liuxiran** [comment]
waiting for infra's reply: https://issues.apache.org/jira/browse/INFRA-22311

**Comment by qsliu2017** [comment]
> waiting for infra's reply: https://issues.apache.org/jira/browse/INFRA-22311

Thanks for your help!!

**Comment by qsliu2017** [comment]
@liuxiran I noticed there is an infra asking what we asking for. IMO we need helps to:
1. **register a cypress dashboard account** to run e2e tests parallel
2. **set** this account in this repo's **secrets**
3. **upgrade this account**. cypress free plan seems too short for our project. cypress offers a discount for open source projects and we can apply for it

**Comment by liuxiran** [comment]
> @liuxiran I notice there is an infra asking what we asking for. IMO we need helps to:
> 
> 1. **register a cypress dashboard account** to run e2e tests parallel
> 2. **set** this account in this repo's **secrets**
> 3. **upgrade this account**. cypress free plan seems too short for our project. cypress offers a discount for open source projects and we can apply for it

@qsliu2017 thanks for your reminder, we will try to apply for an Upgrade account, when there is an result, I will comment here

**Comment by liuxiran** [comment]
Hi @qsliu2017,  after a simple calculation, I found that the free version indeed does not support the dashboard project properly, need to upgrade the account to Team version we need to find support for this costs. Then would you like to send a discuss to our mail list: dev@apisix.apache.org to discuss this with our community：
1. Do you agree with us to do this
2. If we all agree, where can we look for support？from Apache Infra, or we will try to seek support from cypress？

Looking forward to your reply, thanks a lot

**Comment by qsliu2017** [comment]
@liuxiran Thanks! I've sent an email to mail list.

**Comment by liuxiran** [comment]
> @liuxiran Thanks! I've sent an email to mail list.

Hi @qsliu2017 , sorry to forget to mention that before send mail to our mail list , you need to mail to dev-subscribe@apisix.apache.org, and follow the reply to subscribe to the mailing list, then your mail to our mail list can be sent out smoothly, at the same time you can also receive other mails correspondence with mailing lists about our community

**Pull request closed without merging**
