### PR TITLE
chore: improve bug report template

### LINKED ISSUE #944: Improve the Bug Report issue template
# Feature request

Once the info page is added, users could provide more information easily. 

## Describe the solution you'd like

Update the issue template.

## Describe alternatives you've considered

None

## Additional context

related issue or PR

#853 
#850

### PR DESCRIPTION
**Pull request by stu01509**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
Fix #944

### New feature or improvement
- Describe the details and related test reports.
If this issue template can be accepted, I will create another PR to standardize all of APISIX's repo issue templates.

___

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]
LGTM

**Review by nic-chen — APPROVED** [review]
LGTM

**Review by Jaycean — APPROVED** [review]
LGTM

**Review by liuxiran — APPROVED** [review]

**Comment by liuxiran** [comment]
merged, thanks a lot

**Pull request merged**
