### PR TITLE
fix: omit taobao mirror

### LINKED ISSUE #1223: fe: remove npm mirror from taobao
# Feature request

## Please describe your feature

Some dependencies are using taobao as npm mirror, we have to remove them from yarn.lock.

### PR DESCRIPTION
**Pull request by juzhiyuan**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

- Related issues
fix #1223 

just regenerate the whole yarn.lock according to package.json.

### CODE REVIEW

**Review by liuxiran — APPROVED** [review]

**Comment by juzhiyuan** [comment]
What happened to the lint...

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-dashboard/pull/1283/checks?check_run_id=1692687432

**Comment by liuxiran** [comment]
> What happened to the lint...

does the default config of lint changed together with the dependences?

**Comment by juzhiyuan** [comment]
not sure, I need some time to work on it.

**Comment by membphis** [comment]
big PR, please confirm @liuxiran @LiteSun 

image

**Comment by juzhiyuan** [comment]
@membphis Those changes are generated to use the official CDN instead of the Taobao mirror.

**Review by LiteSun — APPROVED** [review]

**Pull request merged**
