### PR TITLE
docs: change year to 2021

### PR DESCRIPTION
**Pull request by krak7602**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches
___
### New feature or improvement
- Updated the year to 2021

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]
Good! CI failed due to https://github.com/apache/apisix-dashboard/pull/1372

**Review by tokers — APPROVED** [review]

**Comment by juzhiyuan** [comment]
Just be patient to wait for #1372

**Review by starsz — APPROVED** [review]

**Comment by liuxiran** [comment]
as #1372 has been merged, you can merge master to resolved the ci failture ^_^, thanks

**Comment by krak7602** [comment]
the test was successful, but the fork I have is several commits behind. Should I close this pr and open another one or will it not affect the main branch. [ sorry for the trouble, this is my first pr]

**Comment by juzhiyuan** [comment]
@krak7602 Hi! Your first PR is going to merge, welcome!

**Pull request merged**
