### PR TITLE
fix(username_regex): cp consumer name regx different with dp

### LINKED ISSUE #2196: can not open consumer with numbers as name
### Issue description

The issue is that you can add a consumer through admin api and his name is 12345.
and if you go to the dashboard you will not be able to change any thing in this consumer configuration.
Here is a created user and I need to change something in its configuration
image

### Expected behavior

//

### How to Reproduce

//

### Screenshots

_No response_

### Environment

- apisix version (cmd: `apisix version`): 2.5
- OS (cmd: `uname -a`): linux ubuntu
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.9.1
- etcd version, if have (cmd: run `etcd --version`): 3.4.13
- apisix-dashboard version, if have: 2.6
- Browser version, if have:

### Additional context

//

### PR DESCRIPTION
**Pull request by zaunist**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

APISIX support consumer name start with number, but APISIX-Dashboard does't support. Does the APISIX-Dashboard need to support consumer that start with number.
And there is the APISIX regex https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L693 

image

After change:

QQ20211202-100229@2x

**Related issues**

fix/resolve #2196 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [x] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by zaunist** [comment]
cc @liuxiran @bzp2010 @LiteSun @juzhiyuan

**Review by juzhiyuan — APPROVED** [review]
LGTM

**Comment by zaunist** [comment]
cc @okaybase

**Review by bzp2010 — APPROVED** [review]

**Comment by okaybase** [comment]
> cc @okaybase

the tip message is updated~

**Comment by zaunist** [comment]
> > cc @okaybase
> 
> the tip message is updated~

thanks

**Review by okaybase — APPROVED** [review]

**Pull request merged**
