### PR TITLE
chore: update setup script

### PR DESCRIPTION
**Pull request by bisakhmondal**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

Removed the part of the script responsible for downloading the apisix dockerfile.

**Related issues**
Combined with #1744 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by nic-chen** [comment]
@bisakhmondal  we should  keep this script, we nee to download the Dockerfile when we need to test with APISIX master branch.

**Comment by bisakhmondal** [comment]
> @bisakhmondal we should keep this script, we nee to download the Dockerfile when we need to test with APISIX master branch.

Hiii. Okay, sounds good. One thing I'd like to address i.e. the compose file has been changed, so if we want to build the apisix image from the downloaded dockerfile, we have to manually update the compose file (just for the testing and again put it back to the original).

As a hack, I think we can do something like `./setup.sh up --afresh` (--afresh an extra flag) which will 
1. Download the dockerfile
2. retag the already present `apache/apisix:2.4-alpine:latest` to `apache/apisix:2.4-alpine:stable`
3. Build an image from the docker file with tag `apache/apisix:2.4-alpine:latest`

A kind of abstraction that doesn't require altering the compose file. When we run `./setup.sh down`, it will revert the steps. 

How does it sound to you :)

**Comment by bisakhmondal** [comment]
Any thoughts here 😄🤡? @nic-chen

**Comment by nic-chen** [comment]
> > @bisakhmondal we should keep this script, we nee to download the Dockerfile when we need to test with APISIX master branch.
> 
> Hiii. Okay, sounds good. One thing I'd like to address i.e. the compose file has been changed, so if we want to build the apisix image from the downloaded dockerfile, we have to manually update the compose file (just for the testing and again put it back to the original).
> 
> As a hack, I think we can do something like `./setup.sh up --afresh` (--afresh an extra flag) which will
> 
> 1. Download the dockerfile
> 2. retag the already present `apache/apisix:2.4-alpine:latest` to `apache/apisix:2.4-alpine:stable`
> 3. Build an image from the docker file with tag `apache/apisix:2.4-alpine:latest` (just to match the name, under the hood, it may use any version of APISIX)
> 
> A kind of abstraction that doesn't require altering the compose file. When we run `./setup.sh down`, it will revert the steps.
> 
> How does it sound to you :)


hi  @bisakhmondal 
Your idea is great. 
But I still think it is enough to keep the current state. 
The current way is relatively clear.
We don’t need to invest too much time in writing this script and maintaining it. 
The benefits are not much, what do you think?

**Comment by bisakhmondal** [comment]
>We don’t need to invest too much time in writing this script and maintaining it.
>The benefits are not much.

+1
Yeah, very true :)
So I think we can close this PR now.

**Review by gxthrj — APPROVED** [review]
I think we can merge it anyway.

**Review by bzp2010 — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
