### PR TITLE
feat(CI): no need to build web after being merged

### PR DESCRIPTION
**Pull request by juzhiyuan**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [ ] New feature provided
- [x] Improve performance

- Related issues
None

### CODE REVIEW

**Comment by liuxiran** [comment]
Not all prs do `merge master`  before they being merged, so IMHO CI can run after pr merges to check if there are any problems in merge action.

**Comment by juzhiyuan** [comment]
🤔 I remember there has one button to let us rebase master before merging, but I couldn't find it recently 😂

**Comment by juzhiyuan** [comment]
image

Hi @liuxiran, just enabled the **Update branch**, could we reconsider the PR?

**Comment by liuxiran** [comment]
> image
> 
> Hi @liuxiran, just enabled the **Update branch**, could we reconsider the PR?

1. I looked up several open source projects
e.g:
[apisix](https://github.com/apache/apisix/blob/0670eff88fdadb4d4a1d306086993557f2e3e3bf/.github/workflows/build.yml#L5)
[skywalking](https://github.com/apache/skywalking/blob/e6265ba5be988c9b4c47252794a3684d544584d0/.github/workflows/ci-it.yaml#L21)
[kubesphere](https://github.com/kubesphere/kubesphere/blob/d814d5db7bde49b44b31ad8ddf14da5517bc0c78/.github/workflows/build.yml#L6)
they all run ci when push to master branch

1. the prs which does not have conflicts with the master branch, IMHO we did not need to do the rebase

but this is just my personal opinion, we can listen to others‘ suggestions. ^_^

**Comment by juzhiyuan** [comment]
why backend CI failed again 😢

@nic-chen

**Pull request closed without merging**
