### PR TITLE
chore: delete unused file

### LINKED ISSUE #1461: feat: Confirm whether the store related functions are still in use. If not, delete them
# Feature request

## Please describe your feature

comment: https://github.com/apache/apisix-dashboard/pull/1452#discussion_r571882686
Confirm whether the store related functions are still in use. If not, delete them.
```
store.NewFilter([]string{"name", name})
store.NewPagination(0, 0)
store.NewQuery(sort, filter, pagination)
store.NewFilterSelector(toRows(ret), query)
```

### LINKED ISSUE #1567: Delete the unused file in internal/core/store
Hello, I found that some files in `internal/core/store` are not used.

Like `selector.go` and `query.go`.

So we can delete them, then we can improve the coverage of the test. 😀

### PR DESCRIPTION
**Pull request by starsz**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [ ] New feature provided
- [x] Improve performance
- [ ] Backport patches

- Related issues
fix #1567 
close #1461
___

### New feature or improvement
- Describe the details and related test reports.
 Delete the unused file in internal/core/store.

### CODE REVIEW

**Review by nic-chen — APPROVED** [review]
LGTM

**Comment by juzhiyuan** [comment]
Hi @Jaycean, would you please have a review when you have time?

**Comment by Jaycean** [comment]
> Hi @Jaycean, would you please have a review when you have time?

no problem.

**Review by Jaycean — APPROVED** [review]
LGTM.

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
