### PR TITLE
feat: update yarn.lock

### PR DESCRIPTION
**Pull request by LiteSun**
Please answer these questions before submitting a pull request

- Why submit this pull request?
- [ ] Bugfix
- [ ] New feature provided
- [x] Improve performance
- [ ] Backport patches

- Related issues

___
### Bugfix
- Description

- How to fix?

___
### New feature or improvement
- Describe the details and related test reports.

___
### Please add the corresponding test cases if necessary.

___
### Backport patches
- Why need to backport?

- Source branch

- Related commits and pull requests

- Target branch

### CODE REVIEW

**Comment by nic-chen** [comment]
image

These checks suddenly appear today and every time it fails.
Could we remove them? @LiteSun

**Comment by LiteSun** [comment]
> image
> 
> These checks suddenly appear today and every time it fails.
> Could we remove them? @LiteSun

ping @juzhiyuan

**Comment by juzhiyuan** [comment]
@nic-chen @LiteSun Hi, Netlify is not required before merging. Please fix the FE E2E first.

**Comment by juzhiyuan** [comment]
Once this PR merged, Netlify will pass. This PR mainly fixes the wrong download links in yarn.lock.

**Review by juzhiyuan — APPROVED** [review]

**Review by nic-chen — APPROVED** [review]

**Comment by LiteSun** [comment]
ping~

**Review by liuxiran — APPROVED** [review]

**Review by Jaycean — APPROVED** [review]
LGTM.

**Pull request merged**
