### PR TITLE
chore: Create route form optimization

### LINKED ISSUE #2167: "Create Route" form optimization
# Feature request
"Create Route" -> "Define API Backend Server" -> "Select Upstream" can automatically select the "None" option according to whether service is configured in the previous form "Define API Request" -> "Service"

## Please describe your feature
When I select a defined service in the form below: 
image
When entering the second form, it let me customize the upstream by default, which makes me very confused whether the service configuration in the previous form is useful.
image
So I think the second form can automatically select the **None** option according to whether the service is configured in the first form.
image
Of course, we can give some tips on the page to tell users that they can actively choose the **Custom** option.

### PR DESCRIPTION
**Pull request by oil-oil**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**
When Service is selected in the form in step 1:
image
The Upstream selector will select "None" by default in the form in step 2:
image

When Service is not selected in the form in step 1:
image
image

**Related issues**

resolve #2167 

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [ ] Have you added corresponding test cases?
- [ ] Have you modified the corresponding document?
- [ ] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by zaunist** [comment]
It's better to add some test cases cover this change. And need to wait all cases passed.

**Comment by oil-oil** [comment]
> It's better to add some test cases cover this change. And need to wait all cases passed.

OK, I'm fixing some test related issues.🧐

**Comment by zaunist** [comment]
@guoqqqi PTAL

**Review by guoqqqi — APPROVED** [review]
also LGTM

**Review by bzp2010 — APPROVED** [review]

**Review by juzhiyuan — APPROVED** [review]

**Review by 1502shivam-singh — APPROVED** [review]

**Pull request merged**
