### PR TITLE
fix: incorrect import paths

### PR DESCRIPTION
**Pull request by juzhiyuan**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [x] Bugfix
- [ ] New feature provided
- [ ] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

This PR aims to fix the broken Route creator, this issue is caused by the invalid import path, and when run building, we don't have a checker to check this.

To prevent this occasional case, we may have `Husky` enabled and check paths.

**Related issues**

fix https://github.com/apache/apisix-dashboard/issues/1889

**Checklist:**

- [x] Did you explain what problem does this PR solves? Or what new features have been added?
- [x] Have you added corresponding test cases? **No need for this issue**
- [ ] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by juzhiyuan** [comment]
Waiting for GitHub Action to be fixed. https://www.githubstatus.com/

**Comment by juzhiyuan** [comment]
It would be great to have a checker here:
1. We could enable Husky to check pre-commit;
2. When changed files contain local cache paths, like `@/.umi/xx`, just throw errors.

**Review by liuxiran — APPROVED** [review]

**Comment by juzhiyuan** [comment]
Hi @Yiyiyimu, this PR just fixed an incorrect path-import, so I request you to review it.

**Review by Yiyiyimu — APPROVED** [review]

**Comment by Yiyiyimu** [comment]
> Hi @Yiyiyimu, this PR just fixed an incorrect path-import, so I request you to review it.

Got it. Approved 😀

**Review by LiteSun — APPROVED** [review]

**Pull request merged**
