### PR TITLE
feat: dashboard support windows

### PR DESCRIPTION
**Pull request by FangSen9000**
Please answer these questions before submitting a pull request, **or your PR will get closed**.

**Why submit this pull request?**

- [ ] Bugfix
- [x] New feature provided
- [x] Improve performance
- [ ] Backport patches

**What changes will this PR take into?**

It is better to use node.js to implement the copy command than cp, which can also be run on Windows.

image

image

**Related issues**

**Checklist:**

- [x] Did you explain what problem does this PR solve? Or what new features have been added?
- [x] Have you added corresponding test cases?
- [x] Have you modified the corresponding document?
- [x] Is this PR backward compatible? If it is not backward compatible, please discuss on the mailing list first

### CODE REVIEW

**Comment by FangSen9000** [comment]
@guoqqqi @Baoyuantop @bzp2010 @SkyeYoung Use node Js is better than cp in implementing the copy command, which can also be run on Windows, which will provide more support for dashboard

**Comment by Baoyuantop** [comment]
Please make CI pass, thanks.

**Comment by FangSen9000** [comment]
> Please make CI pass, thanks.

@Baoyuantop @guoqqqi @bzp2010 @SkyeYoung 

All test cases of Dashboard have been repaired and passed, and the issue#2615 can be closed.

image
image

**Comment by SkyeYoung** [comment]
cc @Baoyuantop @bzp2010

**Review by SkyeYoung — APPROVED** [review]

**Review by Baoyuantop — APPROVED** [review]

**Review by guoqqqi — APPROVED** [review]
Good job!

**Comment by guoqqqi** [comment]
Hello, @FangSen9000 Can you help to resolve the conficts

**Pull request merged**
